### ISSUE TITLE
Tag Releases so they appear in github

### ISSUE THREAD

**Issue by raybooysen** [arackaf/customize-cra#101]
Hi

It would be great if we could tag the commits that are released so that they appear in Github as releases.  This helps a lot in the absence of release notes to see what has changed.

Could we do this going forard?

**Comment by with-heart** [comment]
I'd love to make that happen. Any recommendations on tools for managing that?

**Comment by raybooysen** [comment]
The simplest way is to simply run:
```
git tag v1.2.3
git push origin --tags
```
If you do this with the right commit after publishing to NPM, then it'll automatically appear as a release in github.

**Comment by raybooysen** [comment]
More info here too:
https://help.github.com/en/articles/creating-releases

**Comment by with-heart** [comment]
Got it! I've got the latest version (`0.2.14`) tagged as a release and will make sure to tag future releases as well. Thanks @raybooysen

**Comment by raybooysen** [comment]
Thanks Mark
