### ISSUE TITLE
Break apart single-file index into modules

### ISSUE THREAD

**Issue by with-heart** [arackaf/customize-cra#104]
Currently we have everything located in `index.js` and `test.js`. I'd like to break these files apart, keeping a structure similar to #74. That would give us a file structure like this:

```
.
├── customizers
│  ├── addBabelPlugin.js
│  ├── addBabelPlugin.spec.js
│  ├── addBabelPlugins.js
│  └── addBabelPlugins.spec.js
├── utilities
│  ├── getBabelLoader.js
│  └── getBabelLoader.spec.js
└── index.js
```

**Comment by FezVrasta** [comment]
Feel free to use my PR and complete it, I don't have bandwidth for it unfortunately :-(

**Comment by with-heart** [comment]
@FezVrasta I might just do that! Thanks for coming up with the pattern :)
