### ISSUE TITLE
Add babelExclude function

### ISSUE THREAD

**Issue by with-heart** [arackaf/customize-cra#110]
Similar to `babelInclude`, a user should be able to override the `exclude` config for `babel-loader`.

**Comment by csepulv** [comment]
I was looking for something similar. I found this, which might help
https://github.com/dashed/react-app-rewire-babel-loader#-not-maintained-for-react-app-rewired-v2xx

**Comment by with-heart** [comment]
@csepulv That's perfect, thanks for sharing. This issue will be closed by #141.

Also this is random but I looked at your site and I really love your "Explaining the Joy of Refactoring" image. That's such a great way to explain it.
