### ISSUE TITLE
Make customizer functions pure

### ISSUE THREAD

**Issue by with-heart** [arackaf/customize-cra#120]
`customizer` functions currently directly modify the input `config` while also returning it. We can make this more safe by changing `customizers` to only modify and return a copy.

This would be considered a breaking change, so I'm adding it to the 1.0 release.

**Comment by with-heart** [comment]
Merged into `next` branch in #150

**Comment by with-heart** [comment]
As noted by @FezVrasta, this issue isn't actually closed because spread syntax only shallow copies. Will have to come up with another way to deal with it.

**Comment by FezVrasta** [comment]
I'm not sure but maybe https://www.npmjs.com/package/webpack-merge could help
