### ISSUE TITLE
Chrome debugger stopped

### ISSUE THREAD

**Issue by jkeruzec** [arackaf/customize-cra#13]
Dear all,

I have some problem with Chrome debugger and react.
Whenever I started typing in the console in Chrome while breakpoint debugging, I have this message : 
![image](https://user-images.githubusercontent.com/3499632/47094318-4a7e0680-d22b-11e8-969b-5bae5a8c83b3.png)

This problem is a new problem for me, now my JS file are seen in "static/js", and I think it was not the case before.

I have this configuration : 
```js
const { override, addDecoratorsLegacy, disableEsLint, addBundleVisualizer, addWebpackAlias, adjustWorkbox  } = require("customize-cra");
const path = require("path");

module.exports = override(
	addDecoratorsLegacy(),
	disableEsLint(),
	process.env.BUNDLE_VISUALIZE == 1 && addBundleVisualizer(),
	addWebpackAlias({ ["ag-grid-react$"]: path.resolve(__dirname, "src/shared/agGridWrapper.js") }),
	adjustWorkbox(wb => Object.assign(wb, { skipWaiting: true, exclude: (wb.exclude || []).concat("index.html") }))
);
```
And devDependencies : 
```
"@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-decorators": "^7.1.2",
    "customize-cra": "0.1.1"
```
Do you think it may be linked to some babel/file generation ?

**Comment by arackaf** [comment]
Sorry, not sure why you're getting that. I'm pretty unfamiliar with React dev tools, and this is of course pretty far un-related to customize-cra
