### ISSUE TITLE
addLessLoader does not work with css-loader ^3.0.0

### ISSUE THREAD

**Issue by m-weeks** [arackaf/customize-cra#134]
So with css-loader version 3+, the option `localIdentName` is no longer supported, and the `modules` option has become an object that can contain the `localIdentName` option.

This causes addLessLoader to error if using this version of css-loader because the old `localIdentName` option is still being given:

```js
    {
      test: lessModuleRegex,
      use: getLessLoader({
        importLoaders: 2,
        modules: true,
        localIdentName: localIdentName
      })
    }
```

You can see the change described above here:
https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes

**Comment by with-heart** [comment]
Hi @m-weeks, sorry for taking so long to get back to you. I've added you to the project's contributors for reporting this issue. Thanks for helping out!

I've added this to the [1.0 milestone](https://github.com/arackaf/customize-cra/milestone/1) as this would require a breaking change on our end.

This is related to #138.

**Comment by onlyling** [comment]
Now [create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json#L42) is still using css-loader@2.1.1, need to wait for it to upgrade dependencies.

**Comment by with-heart** [comment]
@onlyling Good catch.

**Comment by with-heart** [comment]
`css-loader` was bumped to `3.2.0` 13 days ago in https://github.com/facebook/create-react-app/pull/7876. If anyone wants to tackle this change, we can plan for including it in a 1.0 release since it would be a breaking change.

**Comment by with-heart** [comment]
#185 has been published under `v1.0.0-alpha.0`. You can get to it using `customize-cra@next`.

**Comment by kunjiang** [comment]
I have trouble in here, but mybe it could change to:
```
 {
      test: lessModuleRegex,
      use: getLessLoader({
        importLoaders: 2,
        modules: {
            localIdentName: localIdentName,
        }
      })
 }
```

**Comment by with-heart** [comment]
Hi @kunjiang, I'm going to close this in favor of #201. Please continue conversation there!
