### ISSUE TITLE
Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by MoonCheung** [arackaf/customize-cra#135]
My project built the application based on `react-app-rewired`, then installed `mobx` again, `mobx-react` dependency package import, error reporting：`Support for the experimental syntax 'decorators-legacy' isn't currently enabled`，When you see an error, install again `@Babel/plugin-proposal-decorators`, `@Babel/plugin-proposal-class-properties`, `@Babel/preset-env`, `Babel-plugin-transform-decorators-legacy` still exists an error after import
```javascript
import CounterView from './CounterView';
  5 |
> 6 | @observer // this decorator is must
    | ^
  7 | class MobxCounter extends React.Component {
  8 |   // 观察者
  9 |   @observable count = 0;
```

.babelrc file:
```javascript
 "presets": [
    "@babel/preset-react",
    "@babel/preset-env",
    ["react-app", {
      "absoluteRuntime": false
    }]
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
    "transform-decorators-legacy"
  ]
```
config-overrides.js file:
```javascript
/* config-overrides.js */
const {
  override,
  fixBabelImports,
  addBabelPresets,
  addBabelPlugins,
  useBabelRc,
  disableEsLint,
  addDecoratorsLegacy
} = require('customize-cra');
const rewireCssModules = require('react-app-rewire-css-modules');
const path = require('path');

...省略

module.exports = override(
  useBabelRc(),
  disableEsLint(),
  //添加装饰器,确保安装了@babel/plugin-proposal-decorators。
  addDecoratorsLegacy(),
  ...addBabelPresets('@babel/preset-react', '@babel/preset-env', [
    'react-app',
    {
      absoluteRuntime: false
    }
  ]),
  ...addBabelPlugins(
    //启用ES7的修改器语法（babel 7), 还有{ "legacy": true }一定不能掉，否则报错
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }]
  ),
  ...省略
);
```

How to solve this problem, please help me, ok?

**Comment by dqu** [comment]
To enable decorators in my project, all I needed to do was add the `addDecoratorsLegacy()` function to `config-overrides.js`, like so:

```
const { override, addDecoratorsLegacy } = require('customize-cra');

module.exports = override(
  addDecoratorsLegacy()
);
```
Make sure you have the Babel plugin for decorators installed as well.
```
npm install --save-dev react-app-rewired
npm install --save-dev customize-cra 
npm install --save-dev @babel/plugin-proposal-decorators
```

`package.json`:
```
...
scripts": {
    "start": "react-app-rewired start",
...
},
"devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "customize-cra": "^0.4.1",
    "react-app-rewired": "^2.1.3"
}
...
```

**Comment by with-heart** [comment]
Hey @dqu, that's a great response! I added you to the project's contributors. Thanks for helping out :)

@MoonCheung, did that fix your issue?

**Comment by MoonCheung** [comment]
Sorry to have kept you waiting, but I haven't solved my problem yet. I wrote `mobx` in `Javascript` language instead of `Typescript` language, and still reported an error: Support for the experimental syntax 'decorators-legacy' isn't currently enabled

config-overrides.js file:
```javascript
/* config-overrides.js */
const {
  override,
  fixBabelImports,
  useBabelRc,
  useEslintRc,
  disableEsLint,
  addDecoratorsLegacy
} = require('customize-cra');
const rewireCssModules = require('react-app-rewire-css-modules');
const path = require('path');

...省略

module.exports = override(
  useBabelRc(),
  useEslintRc(),
  disableEsLint(),
  //添加装饰器,确保安装了@babel/plugin-proposal-decorators。
  addDecoratorsLegacy(),

  ...省略
);
```
.babelrc file No modification for the time being

**Comment by dqu** [comment]
@MoonCheung - I tried to replicate your settings in one of my projects that uses decorators and it worked fine.

```
/* config-overrides.js */
const {
  override,
  fixBabelImports,
  useBabelRc,
  useEslintRc,
  disableEsLint,
  addDecoratorsLegacy
} = require('customize-cra');
//const rewireCssModules = require('react-app-rewire-css-modules');
const path = require('path');

module.exports = override(
  useBabelRc(),
  useEslintRc(),
  disableEsLint(),
  //添加装饰器,确保安装了@babel/plugin-proposal-decorators。
  addDecoratorsLegacy(),

);
```

```
  "devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@svgr/webpack": "^4.3.0",
    "customize-cra": "^0.2.14",
    "react-app-rewired": "^2.1.3"
  }
```

Two things come to mind that could be causing your issue:
1. Some .babelrc file contains settings that are conflicting with `addDecoratorsLegacy()`
1. Something wrong with your `"start": "react-app-rewired start"` react-app-rewired start script? Not sure what would cause that though.

Maybe if you can share your project, I could try helping your troubleshoot it directly.

**Comment by MoonCheung** [comment]
@dqu Thank you for helping me solve the problem, because I am in the `config-overrides` configuration file containing errors caused by the conflict between CRA 2.0 and CRA 1.0, CRA 1.0 has been excluded, and then it can be normal to indicate that the decorator supports

**Comment by josephbuchma** [comment]
@MoonCheung I think I have same issue, can you elaborate how exactly you fixed the problem?
Also, did you manage to get it working with Typescript?

**Comment by josh231101** [comment]
Hey @MoonCheung I have more less the exact same problem, can you help me?
