### ISSUE TITLE
How to use with target electron-renderer?

### ISSUE THREAD

**Issue by nvuhung** [arackaf/customize-cra#136]
I am using the customize-cra with below the config in config-overrides.js file:

```
const {
  addWebpackExternals,
  override,
  fixBabelImports,
  addLessLoader,
  addWebpackAlias,
} = require('customize-cra');
const path = require('path');

const lessPath = path.resolve(__dirname, './src/styles/_variables.less');

module.exports = override(
  addWebpackExternals({ target: 'electron-renderer' }),
  addWebpackAlias({
    '@': path.resolve(__dirname, 'src'),
  }),
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true,
  }),
  addLessLoader({
    javascriptEnabled: true,
    localIdentName:
      process.env === 'prod'
        ? '[name]--[local]___[hash:base64:5]'
        : '[path][name]--[local]___[hash:base64:5]',
    modifyVars: { hack: `true; @import "${lessPath}";` },
  }),
);
```

I am building the electron app with React but I cannot build the production app. 
I have followed this guide: https://github.com/facebook/create-react-app/issues/6782#issuecomment-491743522 but I don't know how to add the config:   config.target = 'electron-renderer'; to the override file. 
Please support me resolve the problem.

**Comment by with-heart** [comment]
Hi @nvuhung. You could create your own function to write the `target` field and add it to the `override` params:

```js
const addWebpackTarget = target => config => {
  config.target = target
  return config
}

module.exports = override(addWebpackTarget('electron-renderer'))
```

Let me know if that works for your use case!

**Comment by nvuhung** [comment]
Thanks @with-heart , this works perfectly 👍 , so I will close this issue

**Comment by with-heart** [comment]
Glad I could help!
