### ISSUE TITLE
worker-loader

### ISSUE THREAD

**Issue by YumcoderCom** [arackaf/customize-cra#137]
I would be obliged if one help me to find the right config for loading the following loader in create-react-app
https://webpack.js.org/loaders/worker-loader/

**Comment by with-heart** [comment]
Hi @YumcoderCom! Once #140 is merged and released, you'll be able to add `worker-loader` like this:

```js
const {override, addWebpackModuleRule} = require('customize-cra')

module.exports = override(
  addWebpackModuleRule(
    {
      test: /\.worker\.js$/,
      use: { loader: 'worker-loader' }
    }
  )
)
```

**Comment by YumcoderCom** [comment]
I would be grateful if you could consider the merge as soon as possible ;)

**Comment by with-heart** [comment]
This is now included in v0.5.0 :)

**Comment by YumcoderCom** [comment]
by the above-mentioned config the following error has thrown:
https://github.com/webpack/webpack/issues/6642

**Comment by with-heart** [comment]
No problem! I'm not super-familiar with how webpack workers operate. 

If the solution from that thread is correct, you should be able to do something like the following:

```js
const {override, addWebpackModuleRule} = require('customize-cra')

module.exports = override(
  config => ({
    ...config,
    output: {
      ...config.output,
      globalObject: 'this'
    },
  }),
  addWebpackModuleRule(
    {
      test: /\.worker\.js$/,
      use: { loader: 'worker-loader' }
    }
  )
)
```

If that doesn't work, you'll want to ask for help from the `webpack` community!

**Comment by jvinhit** [comment]
> No problem!
> 
> If the solution from that thread is correct, you should be able to do something like the following:
> 
> ```js
> const {override, addWebpackModuleRule} = require('customize-cra')
> 
> module.exports = override(
>   config => ({
>     ...config,
>     output: {
>       ...config.output,
>       globalObject: 'this'
>     },
>   }),
>   addWebpackModuleRule(
>     {
>       test: /\.worker\.js$/,
>       use: { loader: 'worker-loader' }
>     }
>   )
> )
> ```
> 
> If that doesn't work, you'll want to ask for help from the `webpack` community because I am not familiar with how workers operate.

it's doesn't work 😢
