### ISSUE TITLE
局部样式

### ISSUE THREAD

**Issue by Ljhhhhhh** [arackaf/customize-cra#138]
How to set the default to local style
ex:[name].module.less  -->[name].less

**Comment by with-heart** [comment]
Hi @Ljhhhhhh, the [current implementation of `addLessLoader`](https://github.com/arackaf/customize-cra/blob/e5e237c401e0c959a811744873c22903d5377505/src/customizers/webpack.js#L109-L188) is not flexible enough to support that change. 

Specifically, there are two [loader objects](https://github.com/arackaf/customize-cra/blob/e5e237c401e0c959a811744873c22903d5377505/src/customizers/webpack.js#L166-L185) defined, one of which is for `.less` and the other which is for `.module.less`. 

We would need to modify that to enable a user to decide how to handle that situation, so they could choose to only use `.less` for modules-enabled files, or something of that nature.

I don't have time to handle this change right now, but if you or someone else would like to pick up the issue, I'd love to help walk you through the changes needed.

**Comment by with-heart** [comment]
Going to close this because I haven't heard back. Feel free to re-open.
