### ISSUE TITLE
Linting Config?

### ISSUE THREAD

**Issue by semb09** [arackaf/customize-cra#14]
Hi

Is there anyway this package could be used to add custom linting rules to a CRA2 app.
By default there are no stylistic rules applied to CRA and no way to add them without ejecting.

Thanks

**Comment by arackaf** [comment]
For sure. PR's open - feel free to add a plugin that updates the lint config as needed. I don't use eslint, so I'm not sure how to do that, but feel free - I usually address PR's pretty quickly.

But are you sure you want stylistic lint rules, as opposed to just using Prettier?

**Comment by FezVrasta** [comment]
This is my attempt but it's not working properly...

```js
const readEslintConfig = () => config => {
  const eslintRule = config.module.rules.filter(
    r => r.use && r.use.some(u => u.options && u.options.useEslintrc !== void 0)
  )[0];
  eslintRule.use[0].options.useEslintRc = true;
  delete eslintRule.use[0].options.baseConfig;
  const rules = config.module.rules.map(
    r =>
      r.use && r.use.some(u => u.options && u.options.useEslintrc !== void 0)
        ? eslintRule
        : r
  );
  config.module.rules = rules;
  return config;
};
```

I get a:

```
./src/serviceWorker.js
  Line 12:  Parsing error: The keyword 'const' is reserved
```

even if my eslint config is properly configured, I guess I'm missing something.
