### ISSUE TITLE
Trying to set the globalObject via config

### ISSUE THREAD

**Issue by bknill** [arackaf/customize-cra#15]
I've run into the problem of create-app-rewired not working with cra 2.0

I need to change the globalObject to get web workers working. 

Previously in create-app-rewired it was quite simple,   config.output.globalObject= `self`

In this, the only mention I found of changing the config was in AdjustWorkbox.. I've tried this below and it's having no effect. Any clues?

```
const { override } = require("customize-cra");
const path = require('path')

module.exports = override(adjustWorkbox((config, env) => {

  config.output.globalObject= `self`
  
  return config
}))
```

**Comment by jgoux** [comment]
Hello @bknill , 

`override` is a function that takes other functions of the shape `(config) => config` as arguments. For example : 
```js
const setGlobalObject = value => config => {
  // mutate config as you want
  config.output.globalObject = value

  // return config so the next function in the pipeline receives it as argument
  return config
}

module.exports = override(setGlobalObject('self'))
```

**Comment by bknill** [comment]
cool thanks
