### ISSUE TITLE
How to configure devServer.before

### ISSUE THREAD

**Issue by wuchaoya** [arackaf/customize-cra#151]
```js
  const addBefore = before => config => {
	config.before =  before
	return config
}

devServer: overrideDevServer(
		addBefore(function (app) {
			apiMocker(app, path.resolve('./src/mock/index.ts'))
		}),
	)
```

Unable to start,  Unexpected token export, error Command failed with exit code 1.

**Comment by wuchaoya** [comment]
```js
devServer: overrideDevServer(
		addBefore(function (app) {
			app.get('/some/path', function(req, res) {
				res.json({ custom: 'response' });
			});
		})
	)
```
I can do it if I do, but I wonder why I don't support it. [mocker-api ](https://www.npmjs.com/package/mocker-api)

**Comment by with-heart** [comment]
Hi @wuchaoya. That's a great implementation. Unfortunately we can't support every possible modification to the `webpack` config object. That would make the api far too large. 

We try to provide the tools that enable you to create your own functions, as you have done here.
