### ISSUE TITLE
flow syntax in web.js files causes errors

### ISSUE THREAD

**Issue by vladp** [arackaf/customize-cra#152]
I am getting an error in JS file that has //@flow 
so the flow syntax is supposed to work (because the necessary presets and plugins are are included in react-scripts)

But for some reason, after I apply the configurations below -- the  webpack / babel does not understand the flow syntax (type definitions in this case).

It seems like babelInclude is not including the subdirectory I am asking to include (it is actually a symlink)

(I am migrating from my custom config-overides.js to this project as it has many more feature than I can do myself)

> 
> SyntaxError: /home/v/devel/mine/myproj/mob/rn.common/src/js.app/mdk/ButtonShim.web.js: Unexpected token, expected ";" (11:5)
> 
>    9 | import {Icon} from './RNVI';
>   10 | 
> > 11 | type RCButtonShim_propTypes = {
>      |      ^
>   12 |   title: string,
>   13 |   onPress: Function,
>   14 |   size?: string,
> 
> 

--
The root of project is
/home/v/devel/mine/myproj/mob/rnweb/app1/cra/    
The above dir contains  config-overide.js .flowconfig node_modules and ./src

my  config-overrides.js

```
const {
  override,
  
  overrideDevServer,
  watchAll,
  removeModuleScopePlugin,
  babelInclude,
  addWebpackAlias
} = require('customize-cra');

const path = require('path');
const paths = require('react-scripts/config/paths');


module.exports = {
  webpack: override(
    /* not needed
    addWebpackResolve ({
          ['extensions']:['.web.js','.js']
        }),
    */
    removeModuleScopePlugin(),
    babelInclude([
      paths.appSrc, 
      path.resolve(__dirname,paths.appSrc+'/js.app') //js.app is a symlink to /home/v/devel/mine/myproj/mob/rn.common/src/js.app/
        ]),

    // add an alias for "ag-grid-react" imports
    addWebpackAlias({
      ['rnjs_common']: path.resolve(__dirname, './src/js.app')
    }),
  ),
  devServer: overrideDevServer(
    // dev server plugin
    watchAll()
  )
};

```
Would appreciate if somebody could point to a way to resolve this.

**Comment by vladp** [comment]
Figured it out.
I needed to replace path.resolve with fs.realPathSync
```

 babelInclude([
      paths.appSrc, 
      fs.realSync(paths.appSrc+'/js.app') //js.app is a symlink to /home/v/devel/mine/myproj/mob/rn.common/src/js.app/
        ]),


```

**Comment by with-heart** [comment]
Glad you were able to figure that out! Good to know.
