### ISSUE TITLE
how to configure publicPath?

### ISSUE THREAD

**Issue by bammoo** [arackaf/customize-cra#154]
how to configure publicPath?

**Comment by with-heart** [comment]
Hi @bammoo. We currently don't have a way to override `publicPath`, though it's something I've been thinking about. What's your use case?

**Comment by with-heart** [comment]
Related to #103

**Comment by ztfstar** [comment]
@gfafei 大佬，您好，请问我用这个setWebpackPublicPath方法设置publicPath为啥不起作用，打包好的js文件依然是绝对路径，就是访问/components/hd-layout 的时候请求的 js对应的url应该是：

http://localhost:6006/static/js/0.chunk.js)
可是现在多了一个 components，如下：

[](http://localhost:6006/components/static/js/0.chunk.js)
<img width="378" alt="tt" src="https://user-images.githubusercontent.com/42028416/128603169-50374d92-02b0-4ef6-b190-aff7f4f4a225.png">

**Comment by gfafei** [comment]
抱歉，太久不用这个，不记得了。建议eject一下，然后研究下webpack的配置。找到问题后再用git rollback回来。

**Comment by leonineli** [comment]
You can control this with the homepage field in your package.json.
"homepage": "./"
