### ISSUE TITLE
How to override the webpack default plugin options?

### ISSUE THREAD

**Issue by jasonOramo** [arackaf/customize-cra#155]
Hi ,

I haven't found a way to override the webpack default plugin option. For example, I want to override some options for this plugin "splitChunks" which is the default used in the webpack4. 
I know there is a api "addWebpackPlugin" which could be used to add new plugin. And I use it to add new plugins, for example "addWebpackPlugin(new BundleAnalyzerPlugin()),".
But how to update the options for the default plugins?

Best Regards

**Comment by with-heart** [comment]
Hi @jasonOramo. We don't currently provide a direct way to modify `webpack.optimization.splitChunks`, but you could easily create a function similar to our `disableChunk` implementation (you can [find that implementation here](https://github.com/arackaf/customize-cra/blob/9c3b12f4591399c176ec48d4897750cd256661be/src/customizers/webpack.js#L202-L212)).

For example:

```js
const setChunksMaxSize = maxSize => config => {
  config.optimization.splitChunks.maxSize = maxSize
  return config
}

module.exports = override(
  setChunksMaxSize(50)
)
```

**Comment by jasonOramo** [comment]
Thanks a lot.
