### ISSUE TITLE
requireEnsure override

### ISSUE THREAD

**Issue by taddj** [arackaf/customize-cra#159]
Is there any way to accomplish this with customize-cra? I am trying to fix an issue as described here https://github.com/wojtekmaj/react-pdf/issues/280

```
module.exports = function override(config) {
  config.module.rules[0].parser.requireEnsure = true
  return config
}
```

**Comment by with-heart** [comment]
Hi @taddj, you should be able to resolve your issue with something like this:

```js
const { override, addDecoratorsLegacy } = require("customize-cra");

const enableRequireEnsure = () => config => {
  config.output.globalObject = 'this'
  config.module.rules[0].parser.requireEnsure = true
  return config
}

module.exports = override(
  addDecoratorsLegacy(),
  enableRequireEnsure(),
);
```

**Comment by taddj** [comment]
That worked!

**Comment by with-heart** [comment]
Awesome! Glad that worked for you. 

I've added you to our contributors list for asking a question! Thanks for taking part :)

**Comment by thomastaechoi** [comment]
I had this same issue. Thank you @with-heart 😄
