### ISSUE TITLE
Log the transformed configuration?

### ISSUE THREAD

**Issue by badgerwithagun** [arackaf/customize-cra#160]
I'm hitting some issues where it would be extremely useful to see the resulting webpack configuration pre and post transform during the build.  Is this possible?

**Comment by with-heart** [comment]
Hi @badgerwithagun! I actually love this idea and want to turn it into a util function we include as part of the API, but for now you could do this:

```js
const {override, addBabelPlugin} = require('customize-cra')

// log the config and then return it
const tap = () => config => {
  console.log(JSON.stringify(config, null, 2))
  return config
}

module.exports = override(
  tap(), // post-transform
  addBabelPreset('@babel/preset-env'),
  tap(), // pre-transformation
)
```

**Comment by badgerwithagun** [comment]
Nice! Thanks @with-heart.

**Comment by with-heart** [comment]
No problem! I opened #165 to add this to the api. I've added you to the contributors list in our `readme` for the idea, thanks for participating! :)
