### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by deng302949** [arackaf/customize-cra#166]
```js
const {
    override,
    addWebpackModuleRule,
    useEslintRc,
} = require('customize-cra');

module.exports = override(
    config => ({
        ...config,
        output: {
            ...config.output,
            globalObject: 'this',
        },
    }),
    addWebpackModuleRule({
        test: /\.worker\.js$/,
        use: { loader: 'worker-loader' },
    }),
    useEslintRc()
);
```

`addWebpackModuleRule`|`useEslintRc` ---Use these two together.  error is `e.use.some is not a function`

**Comment by with-heart** [comment]
Hi @deng302949! I am unable to reproduce your error. Could you tell me what versions of `react-scripts`, `react-app-rewired`, and `customize-cra` you're using?

**Comment by deng302949** [comment]
"customize-cra": "^0.5.0",
    "react-app-rewired": "^2.1.3",  
@with-heart  and a demo  link: https://github.com/evgeny-nadymov/react-webworker-pako

**Comment by deng302949** [comment]
"react-scripts": "2.1.8",   and  "react-scripts": "3.1.1"  not competent

**Comment by with-heart** [comment]
@deng302949 is this working for you now?
