### ISSUE TITLE
how to use this to config publicpath in my own project

### ISSUE THREAD

**Issue by fireairforce** [arackaf/customize-cra#167]
i want to put my static resource into a publichpath just like the config in [webpack](https://webpack.js.org/guides/public-path/#root)

**Comment by with-heart** [comment]
Hi @fireairforce, this was recently added by @gfafei in #161 as `setWebpackPublicPath`. Upgrade to `customize-cra@0.7.0` to use it!

**Comment by fireairforce** [comment]
thx,i will try
