### ISSUE TITLE
When I use setWebpackPublicPath to set a cdn path,the route will add a prefix `/`

### ISSUE THREAD

**Issue by fireairforce** [arackaf/customize-cra#168]
setWebpackPlugin can add a prefix `/` in your cnd site,if I set the publicPath as a cdn path just like `http://xxx.com`,the result will be `src="/http://xxx.com/..."`,so i want to remove the prefix when i set the path as a cdn path just like [webpack output config](https://webpack.js.org/configuration/output/#outputpublicpath)

**Comment by fireairforce** [comment]
I try to solve this problem by myself,so i open a [pull request](https://github.com/arackaf/customize-cra/pull/169)

**Comment by with-heart** [comment]
Closed by #169
