### ISSUE TITLE
How to set  output path

### ISSUE THREAD

**Issue by wsxgs** [arackaf/customize-cra#170]
I want to change output path, but no way

**Comment by yangzhennupt** [comment]
in you config-overrides.js
```
const publicPathPlugin = (config, env) => {
  config.output = {
    filename: "[name].[hash:8].js",
    path: path.resolve(__dirname, "dist"),
    publicPath: '/',
    chunkFilename: "[name].[hash:8].async.js",
  }
  return config
}
```
then 
```
module.exports =  {
  webpack: override(
  publicPathPlugin， // if you need  env ,  must set your plugin first, because  customize-cra's api not exports it
 )
}
```

**Comment by wsxgs** [comment]
I had try this way, the file in public folder can`t  build to  set folder

**Comment by yangzhennupt** [comment]
> I had try this way, the file in public folder can`t build to set folder

I think you shoule use path, not publicPath

**Comment by yangzhennupt** [comment]
> I had try this way, the file in public folder can`t build to set folder

i think you should use path , not publicPath;  publicPath just add prefix to you resource file path

**Comment by wsxgs** [comment]
not publicPath， public is the filder use store  static file, link  index.html 。

**Comment by wsxgs** [comment]
function copyPublicFolder() {
  fs.copySync(paths.appPublic, paths.appBuild, {
    dereference: true,
    filter: file => file !== paths.appHtml,
  });
}
this is the code, where i can`t change

**Comment by mahuimable** [comment]
I have tried it , no success.

**Comment by with-heart** [comment]
Are you talking about [`output.path`](https://webpack.js.org/configuration/output/#outputpath)?

**Comment by with-heart** [comment]
If so, you could try something like this:

```js
const setOutputPath = path => config => {
  config.output = { ...config.output, path }
  return config
}
```

**Comment by ibsusu** [comment]
```
const publicPathPlugin = () => config => {
  let buildPath = './build';

  config.output = {
    path: path.join(__dirname, buildPath)
  };
  config.plugins.push(new WriteFilePlugin());
  fs.removeSync(buildPath);
  fs.copySync('./public/', buildPath);

  return config;
};
```

```
module.exports =  {
  webpack: override(
  publicPathPlugin， // if you need  env ,  must set your plugin first, because  customize-cra's api not exports it
  ...
 )
}
```

This works.  With-heart got it.  kinda funny tbh.

**Comment by with-heart** [comment]
Glad that worked for you @ibsusu! :)

Gonna close this. @wsxgs if you still have issues feel free to re-open or start a new issue.

**Comment by kafkahw** [comment]
For those coming here late like me: [react-app-rewired](https://github.com/timarney/react-app-rewired#4-paths-configuration---development--production) now supports overriding `paths` in `config-overrides.js`:
```js
module.exports = {
  // The paths config to use when compiling your react app
  //  for development or production.
  paths: function(paths, env) {
    // ...add your paths config
    paths.appBuild = path.resolve(__dirname, 'lib');
    return paths;
  }
}
```

Related comment: https://github.com/timarney/react-app-rewired/issues/441#issuecomment-607807668

**Comment by erichDuanET** [comment]
> For those coming here late like me: [react-app-rewired](https://github.com/timarney/react-app-rewired#4-paths-configuration---development--production) now supports overriding `paths` in `config-overrides.js`:
> 
> ```js
> module.exports = {
>   // The paths config to use when compiling your react app
>   //  for development or production.
>   paths: function(paths, env) {
>     // ...add your paths config
>     paths.appBuild = path.resolve(__dirname, 'lib');
>     return paths;
>   }
> }
> ```
> 
> Related comment: [timarney/react-app-rewired#441 (comment)](https://github.com/timarney/react-app-rewired/issues/441#issuecomment-607807668)

It works! Thanks
The others will still generate the ‘build‘ directory
