### ISSUE TITLE
I want use 'antd' and 'ant-moible' both,how to do it?

### ISSUE THREAD

**Issue by paauw0** [arackaf/customize-cra#173]
module.exports = {
    webpack: override(
        removeModuleScopePlugin(),
        fixBabelImports(
            [
                'import',
                {
                    libraryName: 'antd',
                    libraryDirectory: 'es',
                    style: true,
                },
                'ant'
            ]
        ),
        fixBabelImports(
            [
                'import',
                {
                    libraryName: 'antd-mobile',
                    libraryDirectory: 'es',
                    style: true,
                },
                'ant-mobile'
            ]
        ),
        addLessLoader({
            javascriptEnabled: true,
            modifyVars: {
                '@primary-color': '#333'
            },
            localIdentName: '[local]--[hash:base64:5]'
        }),
   ),
   devServer: overrideDevServer(
        // dev server plugin
        watchAll()
    )
}

this is my code,'babel-plugin-import' is install, and it throw an error:
You are using a whole package of antd-mobile, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

**Comment by with-heart** [comment]
Hi @paauw0! This appears to be an issue with `antd-mobile` and not `customize-cra`. I suggest you open an issue at [`ant-design-mobile`](https://github.com/ant-design/ant-design-mobile) for more help.

**Comment by leesren** [comment]
It work for like this. @paauw0

```js
const { override, addBabelPlugin, addLessLoader } = require('customize-cra')
/*
 * ps: customize-cra 的 fixBabelImports不支持同时导入两个 import， 看了源码，修改下
 * 增加一个 unique 就行
 */
const myFixBabelImport = (libraryName, options, uniqueName) =>
  addBabelPlugin([
    'import',
    Object.assign(
      {},
      {
        libraryName,
      },
      options
    ),
    `fix-${uniqueName || libraryName}-imports`,
  ])


module.exports = override(
  myFixBabelImport(
    'import',
    {
      libraryName: 'antd-mobile',
      style: true,
    },
    'antd-mobile'
  ),
  myFixBabelImport(
    'import',
    {
      libraryName: 'antd',
      style: true,
    },
    'antd'
  ),

  addLessLoader({
    lessOptions: {
      javascriptEnabled: true,
      modifyVars: {
        '@brand-primary': '#ff5722',
        '@brand-primary-tap': '#ffccbc',
        '@color-text-base-inverse': '#3f51b5',
      },
    },
  })
)


```
