### ISSUE TITLE
Npm run build runs forever ?

### ISSUE THREAD

**Issue by madwill** [arackaf/customize-cra#18]
Hi everyone!

Thanks for creating this! Allowing us to try CRA2. I have made the switch and npm start works great but somehow when its time to create a build it appears the build stop somewhere. 

Is there any way to debug what is happening? My reason for customize-cra was mobx. Thinking of going decorator-less right now. 

tried this config:
```

const rewireMobX = require('react-app-rewire-mobx');
const { override, addDecoratorsLegacy, disableEsLint, addBundleVisualizer, addWebpackAlias, adjustWorkbox } = require("customize-cra");
const path = require("path");

/* config-overrides.js */
module.exports = function override(config, env) {
  config = rewireMobX(config, env);
  return config;
}

module.exports = override(
  addDecoratorsLegacy(),
  disableEsLint(),  
);
```

and this one
```

const { override, addDecoratorsLegacy, disableEsLint, addBundleVisualizer, addWebpackAlias, adjustWorkbox } = require("customize-cra");
const path = require("path");

module.exports = override(
  addDecoratorsLegacy(),
  disableEsLint(),
 
);

```

Did i get something wrong ?

**Comment by madwill** [comment]
Turns out disabling sourcemap allows it to build !

`GENERATE_SOURCEMAP=false yarn build`

Not sure what happened here but at least I can build now.

**Comment by arackaf** [comment]
Glad you figured it out!
