### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by chemitaxis** [arackaf/customize-cra#189]
Hi, we have this configuration, in our `config-overrides.js`:

```
const rewireYarnWorkspaces = require('react-app-rewire-yarn-workspaces');
const rewireStyledComponents = require('react-app-rewire-styled-components');
const {
  override,
  addDecoratorsLegacy,
  disableEsLint,
  useBabelRc
} = require('customize-cra');

const styledComponents = obj => config => {
  config = rewireStyledComponents(config, process.env.NODE_ENV, obj);
  return config;
};

const yarnWorkspaces = config => {
  config = rewireYarnWorkspaces(config, process.env.NODE_ENV);
  return config;
};

module.exports = override(
  styledComponents({
    displayName: process.env.NODE_ENV !== 'production'
  }),
  addDecoratorsLegacy(),
  disableEsLint(),
  useBabelRc(),
  yarnWorkspaces
);
```

And this is our `.babelrc` file:

```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "babel-plugin-styled-components",
    "@babel/plugin-proposal-decorators",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-modules-commonjs",
    "@babel/plugin-transform-runtime"
  ]
}
```

I have installed `async` library, and we have an error like this:

> ReferenceError: exports is not defined

This is the code of the package on **node_modules**:

![Screenshot 2019-11-20 at 19 28 58](https://user-images.githubusercontent.com/1420409/69266735-072f5d80-0bcc-11ea-8165-f2cce18c18ec.png)

What I'm doing wrong? Thank you so much!!

**Comment by with-heart** [comment]
Hi @chemitaxis, I think you might need to use [`async-es`](https://www.npmjs.com/package/async-es).

> This version of the package is optimized for building with webpack. If you use Async in Node.js, install async instead.

Give that a try and let me know if that fixes your issue!

**Comment by chemitaxis** [comment]
Solved @with-heart after removing yarnWorkspaces.... one last question, customize-cra works out of the box with yarn workspaces? Thanks

**Comment by with-heart** [comment]
`customize-cra` should work fine anywhere that `create-react-app` does. Whether `create-react-app` supports it is a much trickier question. You can find more info in this thread: https://github.com/facebook/create-react-app/issues/1333

I wrote [`react-app-rewire-workspaces`](https://github.com/with-heart/react-app-rewire-workspaces) and I believe that was working 9 months ago, but I haven't touched it since then, so I'm not sure if it still works.

**Comment by abrkn** [comment]
@with-heart Was your https://github.com/with-heart/react-app-rewire-workspaces allowing importing shared TypeScript code from CRA? If so, do you have a demo or recall how?
