### ISSUE TITLE
[Discussion] Global API and ecosystem

### ISSUE THREAD

**Issue by jgoux** [arackaf/customize-cra#2]
Hello,

As we're starting again from scratch, it would be a good time to think about the API we want to provide to rewired CRA consumers.

I'd like `customize-cra` to take a more functional approach so we just have to import a bunch of `addThing()`, provide their specifics options, and we're good to go! 🚀 

This is what I have in mind : 

```js
// fantasy organization xD
const { override } = require('@react-app-rewired/core')
const addReactHotLoader = require('@react-app-rewired/add-react-hot-loader')
const addEmotion = require('@react-app-rewired/add-emotion')
const addBundleVisualizer= require('@react-app-rewired/add-bundle-visualizer')

module.exports = override(
  addReactHotLoader , /* no options */
  addEmotion(), /* can have options, here none given so falling back to emotion's defaults */
  addBundleVisualizer({ reportFilename: 'bundle.html' })
)
```

The `override` function is an helper providing the (config, env) to all the functions in the pipeline.

The `addX` functions have to respect two criterias : 
- Take their specific options and return a function accepting `(config, [env])`. If they don't have any options then you can just write the `(config, [env])` directly.
- Always return the altered `config` object.

And that's it!

The implementation of `override` is : 
```js
const { flow, curry } = require('lodash')

function override(...pipeline) {
  return function(config, env) {
    return flow(
      ...pipeline.map(f => {
        const curried = curry(f, 2)
        return curried(curry.placeholder, env)
      })
    )(config)
  }
}
```

And here is an example of "addX" library for `webpack-bundle-visualizer` : 
```js
const { /* re-exported from lodash for convenience */ merge } = require('@react-app-rewired/core')
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin

module.exports = function addBundleVisualizer(options) {
  const defaultOptions = {
    analyzerMode: 'static',
    reportFilename: 'report.html'
  }
  return function(config) {
    config.plugins.push(
      new BundleAnalyzerPlugin(merge(defaultOptions, options))
    )
    return config
  }
}
```

Also, installing `@react-app-rewired/core` would be enough to get started with the `scripts` in `package.json` (either we include `react-app-rewired` or we restart from scratch...)

What do you think? 💡

**Comment by benedyktdryl** [comment]
This looks awesome. Let me know if you need any help.

IMO methods passed to `override` should be always executed, not passed as reference to method, so we will have always same API, means we can avoid confusion. Also I would call module with related methods `utils` as `core` sounds like something internal.

What do you think?

```javascript
const { override } = require('@react-app-rewired/utils')

const addReactHotLoader = require('@react-app-rewired/add-react-hot-loader')
const addEmotion = require('@react-app-rewired/add-emotion')
const addBundleVisualizer = require('@react-app-rewired/add-bundle-visualizer')

module.exports = override(
  addReactHotLoader() , /* no options, still, same API - we are passing result of execution */
  addEmotion(), /* can have options, here none given so falling back to emotion's defaults */
  addBundleVisualizer({ reportFilename: 'bundle.html' })
)
```

**Comment by jgoux** [comment]
@benedyktdryl I went with the `core` naming because of this : 

> Also, installing @react-app-rewired/core would be enough to get started with the scripts in package.json

Also, `override ` would be the central nerve of this API so I wouldn't consider it a simple utility IMO. 😄

I agree with you on `methods passed to override should be always executed`, I hesitated with it too. The less API surface, the better!

**Comment by jgoux** [comment]
@arackaf 

You could also pass a lambda, as `override` takes `(config, [env]) => config` functions.

```js
module.exports = override(
    config => process.env.BUNDLE_VISUALIZE == 1 ? addBundleVisualizer(config) : config
    addDecoratorsLegacy(),
    disableEsLint(),
    addWebpackAlias({ ["ag-grid-react$"]: path.resolve(__dirname, "src/shared/agGridWrapper.js") })
  )
};
```

**Comment by arackaf** [comment]
Oh - I like that a lot.  Thanks!

**Comment by arackaf** [comment]
Hey - great stuff - thanks a ton. Version 0.1.0-beta3 is out, with the override above, working.

Only slight hiccup is the conditional application of the bundle visualizer.  Would love to hear thoughts there. As far as I can tell, my only choices are to break the API for that specific plugin, or else live with the double invocation.

```js
const { override, addDecoratorsLegacy, disableEsLint, addBundleVisualizer, addWebpackAlias } = require("customize-cra");
const path = require("path");

module.exports = override(
  addDecoratorsLegacy(),
  disableEsLint(),
  config => (process.env.BUNDLE_VISUALIZE == 1 ? addBundleVisualizer()(config) : config),
  addWebpackAlias({ ["ag-grid-react$"]: path.resolve(__dirname, "src/shared/agGridWrapper.js") })
);
```

**Comment by jgoux** [comment]
I think the API is simple enough that way.

For more complicated / custom cases, I'd expect the users to write their own function for clarity : 

```js
const { override, addDecoratorsLegacy, disableEsLint, addBundleVisualizer, addWebpackAlias } = require("customize-cra");
const path = require("path");

module.exports = override(
  addDecoratorsLegacy(),
  disableEsLint(),
  customAddBundleVisualizer,
  addWebpackAlias({ ["ag-grid-react$"]: path.resolve(__dirname, "src/shared/agGridWrapper.js") })
);


function customAddBundleVisualizer(config) {
  return process.env.BUNDLE_VISUALIZE == 1 ? addBundleVisualizer()(config) : config
}
```

IMO it's better to provide a one simple way for composing the "addX" functions and let the users build on top of it if needed.

**Comment by benedyktdryl** [comment]
While API should be minimal, I think this is quite good to have small utils like @jgoux provided.

I remember there is existing library for operating on Webpack config. Maybe we should allow / make easier to use it or provide similar API for Webpack/Babel configuration handling?

**Comment by arackaf** [comment]
@jgoux I'm happy enough with things as they are, but this tweet

https://twitter.com/stevenlangbroek/status/1047452160185815041

did make me wonder if we couldn't do better, for free. Couldn't `override` just detect the return value of 

`return curried(curry.placeholder, env);`

and if it's a function, surmise that something like the above has happened, and then just call it again to get the true return value?

**Comment by jgoux** [comment]
@arackaf Just so I'm sure about the final syntax expected, is it : 
```js
module.exports = override(
  process.env.BUNDLE_VISUALIZE == 1 && addBundleVisualizer()
)
```
?

In this case yes we can change `override` to handle the falsy case : 
```diff
const { flow, curry } = require('lodash')

function override(...pipeline) {
  return function(config, env) {
    return flow(
      ...pipeline.map(f => {
+        if (f === false) {
+         return a => a
+        }
        const curried = curry(f, 2)
        return curried(curry.placeholder, env)
      })
    )(config)
  }
}
```

**Comment by arackaf** [comment]
That's not what I was thinking, but it's a whole lot better. Good stuff - thanks.

**Comment by jgoux** [comment]
Now I'm wondering what was the reasoning for introducing the `env` parameter in react-app-rewired? (maybe @timarney can answer here)

Is it just a shortcut / alias for `process.env.NODE_ENV` ?

If we get ride of `env` we could do : 
```js
const { flow } = require('lodash')

function override(...pipeline) {
  return flow(...pipeline.map(f => (f === false ? a => a : f)))
}
```

And `addX` function relying on `env` could rely on `process.env.NODE_ENV` directly.

**Comment by arackaf** [comment]
That seems reasonable, and much nicer. Hopefully Tim can let us know if we're missing something

**Comment by StevenLangbroek** [comment]
I'd name `...pipeline` something more descriptive maybe. Plugins?

**Comment by StevenLangbroek** [comment]
Sorry to barge in on the discussion haha. At my dayjob I'm trying to balance the more esotheric approaches to FP with readability, and saw some minor things:

- If you use `lodash/fp`, immutability is guaranteed so you don't have to clone
- You're cloning the plugins list twice
- Doesn't really need flow

```js
const applyPlugin = curry((config, plugin) => plugin(config));

const override = (...plugins) => (config) =>
  plugins.filter(identity).map(applyPlugin(config));
```

Whether you write it like that, or more lodash'y like so is up to you:

```js
const override = (...plugins) => config => flow(compact, applyPlugin(config))(plugins)
```

**Comment by StevenLangbroek** [comment]
Gheh, that `map` is actually `filter(identity)`.

**Comment by arackaf** [comment]
@StevenLangbroek thanks a ton for those fp suggestions. Not sure why you deleted them. I'll repost here, unless you really want them gone - I hope not though - I definitely plan to go over this closely.

---

Sorry to barge in on the discussion haha. At my dayjob I'm trying to balance the more esotheric approaches to FP with readability, and saw some minor things:

If you use lodash/fp, immutability is guaranteed so you don't have to clone

You're cloning the plugins list twice

Doesn't really need flow

```js
const applyPlugin = curry((config, plugin) => plugin(config));

const override = (...plugins) => (config) =>
  plugins.filter(identity).map(applyPlugin(config));
```

Whether you write it like that, or more lodash'y like so is up to you:

```js
const override = (...plugins) => config => flow(compact, applyPlugin(config))(plugins)
```

**Comment by timarney** [comment]
> Now I'm wondering what was the reasoning for introducing the env parameter in react-app-rewired? (maybe @timarney can answer here)

In practice I don't think env is used much and yes it's just `process.env.NODE_ENV` 

I would remove.

https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/scripts/start.js

**Comment by arackaf** [comment]
Thanks a ton. This is really coming together!

**Comment by timarney** [comment]
One thing to note if you haven't picked up on it already.  People have published modules using react-app-rewire-SOME-PACKAGE .  Makes it easier to find the config mods via NPM search.  Also https://github.com/timarney/react-app-rewired#community-maintained-rewires

Nice touch regardless of what name the project uses in my opinion.

**Comment by jgoux** [comment]
> That seems reasonable.
> 
> @jgoux you forgot to call the result of `flow` with config, but yeah - that'll be great if there's no good reason to keep env around.

`flow(...plugins)` returns a function taking parameters, and pass them to the first plugin in the pipeline. So no need to pass the config in this case as it will be provided by `react-app-rewired`! 👍 

As for registering the organization, it's a whole new world for me as well... But I'm sure we can find the right way together! ✌️

**Comment by StevenLangbroek** [comment]
@arackaf because the code is wrong. My snippet ends up with an array of return values from `map(applyPlugin(config))`, which I doubt is what needs to happen. @jgoux's code is correct, it just took me a while to realize I'd been looking at it wrong.

**Comment by arackaf** [comment]
I had a similar experience (code deleted from comment)

fp is hella hard when you're not used to it. Even when you are, it seems :)

**Comment by jgoux** [comment]
@arackaf FP is especially hard in JS because it's not strongly typed. Doing FP in Haskell or PureScript is a joy because you just need to connect the types! 😍

**Comment by arackaf** [comment]
@jgoux - here's what I have currently, published in 0.1.0-beta5, along with a PR to allow for options to be passed to the bundle visualizer

`const override = (...plugins) => config => flow(...plugins.map(f => f || (a => a)))(config);`

I figured there's no need to limit it to precisely false - `null` should probably work too, in case someone decides to do 

`process.env.BUNDLE_VISUALIZE == 1 ? addBundleVisualizer() : null`

**Comment by viral-sh** [comment]
@jgoux This project seems promising! :+1: Would love to contribute to it!

Some thoughts,

1. The idea of an independent `@react-app-rewired/core` seems better than depending on the original `react-app-rewired` for scripts. Since `react-app-rewired` is not going to be maintained or might have legacy code, we shouldn't be depending on it.
2. To support multiple version of rewiring (older & future) maybe we allow imports like `@react-app-rewired/core/v2` and `@react-app-rewired/core/vX`.
This way we can support multiple versions of `CRA`.
3. The plugins can get a version number param based on which they customize wiring if needed for various versions

**Comment by arackaf** [comment]
@viral-sh hm - well like you said, react-app-rewired is not really maintained. 

I'd say that if CRA ever changes so deeply that the old (react-app-rewired) code no longer works, then at that time we'll definitely have to make some changes, either here, or in the rewired codebase if Time will allow someone to take the project over.

For now though I'd be keen on keeping things as simple as possible.

That said, if you're wanting to help contribute, there's all sorts of new features that could be added: overriding eslint configuration (rather than just turning it off), and, well, anything else people might want - there seems to be a crap-ton of neighboring plugins listed in the rewired docs.

**Comment by svicalifornia** [comment]
Also, [this comment above](https://github.com/arackaf/customize-cra/issues/2#issuecomment-426661858) proposed that falsy plugins should be ignored by 'override'. I agree, but the code diff suggested matches only `false` values, whereas falsy values include any value that would not be considered true in an `if` condition, including `0`, `""`, `null`, and `undefined`.

The code to check this should simply be:

```js
if (!f) { ...
```

**Comment by arackaf** [comment]
Tim himself said we could safely get rid of the env argument, and let plugins just reference process.env as needed.  Backward compat isn't really a concern here, since the react-app-rewired plugins don't really work with CRA 2 any, which is why this project exists.

The final code wound up ignoring any falsy values at all, as you proposed 

https://github.com/arackaf/customize-cra/blob/master/index.js#L72

**Comment by svicalifornia** [comment]
Yes, I saw Tim’s comment, and we all agree that new plugins will look cleaner without the `env` argument. However, you could still pass the old `env` argument in, and new plugins that don’t need it will just ignore it. (It’s perfectly legal in JavaScript to pass two arguments to a function which only takes one argument.)

If you really want a clean break from all of the old plugins, or at least to force them to update to work with customize-cra, then you can leave this as is. I just thought there was a chance that this new `override` syntax would get added to the next version of react-app-rewired, and if so, then it should pass `env` to each plugin to support the plugins that rely on that argument. (Again, any plugins that only take `config` can still be called with both args and will just ignore the second arg.)

**Comment by arackaf** [comment]
> It’s perfectly legal in JavaScript to pass two arguments to a function which only takes one argument.

Understood, it just simplified the override code quite a bit.  And again, the assumption was that just about none of the old plugins would work anyway, so they'd already need to be re-written.

**Comment by svicalifornia** [comment]
That's all fine. Plugins can be updated to use `process.env.NODE_ENV` when they are updated for CRA 2.0.

However, I hope plugin authors don't split each plugin into separate CRA1 and CRA2 builds. Some app projects may need to stay on CRA1 for a while (especially if they made webpack customizations with react-app-rewired), and it would be nice if plugins could be "universal" — automatically detect the CRA version and apply the appropriate config changes.

If each plugin splits into separate CRA1 and CRA2 artifacts in npm, it will make a mess of the package namespace, and further scare a lot of companies (including some of my clients) away from a rewired approach, given that many are already apprehensive about leaving the safe confines of CRA.

**Comment by arackaf** [comment]
Closing this - but if anyone else has inputs here, feel free.
