### ISSUE TITLE
how to support stylus ？

### ISSUE THREAD

**Issue by Alicevia** [arackaf/customize-cra#203]
we can support less by addLessLoader, so  what about stylus ?

**Comment by dehimer** [comment]
I saw pr: https://github.com/arackaf/customize-cra/pull/144/files#diff-44cfd4ff2f95728f40be4a64ecdb55fe
And do not understand why is it closed?

**Comment by Alicevia** [comment]
> I saw pr: https://github.com/arackaf/customize-cra/pull/144/files#diff-44cfd4ff2f95728f40be4a64ecdb55fe
> And do not understand why is it closed?

thanks,     It seems that someone has raised same question,  and he tried to solve this problem, 
Some more times , stylus should be added in it

**Comment by dehimer** [comment]
I have moved code of pr to https://www.npmjs.com/package/customize-cra-add-stylus-loader
Just install and use it

**Comment by dehimer** [comment]
> > I saw pr: https://github.com/arackaf/customize-cra/pull/144/files#diff-44cfd4ff2f95728f40be4a64ecdb55fe
> > And do not understand why is it closed?
> 
> thanks, It seems that someone has raised same question, and he tried to solve this problem,
> Some more times , stylus should be added in it

I have moved code of pr to https://www.npmjs.com/package/customize-cra-add-stylus-loader
Just install and use it. I tested it on my work project and it is work fine.

**Comment by Alicevia** [comment]
oh! thanks dehimer and DayDarkDark

**Comment by DayDarkDark** [comment]
@dehimer @Alicevia  
hello,  i'm lazy to  answer, it can work , and I hava an other solution
`
const { override, fixBabelImports } = require('customize-cra')

const stylus = () => config => {
  const stylusLoader = {
    test: /\.styl$/,
    use: [
      {
        loader: 'style-loader'
      }, {
        loader: 'css-loader',
      }, {
        loader: 'stylus-loader'
      }
    ]
  }
  const oneOf = config.module.rules.find(rule => rule.oneOf).oneOf
  oneOf.unshift(stylusLoader)
  return config
}


module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: 'css',
  }),
  stylus()
)
`

**Comment by dehimer** [comment]
> @dehimer @Alicevia
> hello, i'm lazy to answer, it can work , and I hava an other solution
> 
> ```js
> const { override, fixBabelImports } = require('customize-cra')
> 
> const stylus = () => config => {
>   const stylusLoader = {
>     test: /\.styl$/,
>     use: [
>       {
>         loader: 'style-loader'
>       }, {
>         loader: 'css-loader',
>       }, {
>         loader: 'stylus-loader'
>       }
>     ]
>   }
>   const oneOf = config.module.rules.find(rule => rule.oneOf).oneOf
>   oneOf.unshift(stylusLoader)
>   return config
> }
> 
> 
> module.exports = override(
>   fixBabelImports('import', {
>     libraryName: 'antd',
>     libraryDirectory: 'es',
>     style: 'css',
>   }),
>   stylus()
> )
> ```

Thank you! I will need to update code:)

**Comment by DayDarkDark** [comment]
@dehimer Thank you for using
