### ISSUE TITLE
How to add babel plugin?

### ISSUE THREAD

**Issue by littlehome-eugene** [arackaf/customize-cra#228]
I'm hitting ` Support for the experimental syntax 'classProperties' isn't currently enabled` 

I need to add something like the following to my webpack config. 

https://github.com/babel/babel/issues/8655

    {
      loader: 'babel-loader',
      options: {
        "presets": [
          "@babel/preset-env",
          "@babel/preset-react",
          {
            "plugins": [
              "@babel/plugin-proposal-class-properties"
            ]
          }
        ],
      },
    }

I tried the following and a few variations but won't work..

     module.exports = override(
       ...addBabelPresets("@babel/preset-env", "@babel/preset-react"),
       ...addBabelPlugins('@babel/plugin-proposal-class-properties'),
       # other lines omitted for brevity
    )

I also tried adding it to `package.json` and to `babel.config.js` but no avail..

**Comment by littlehome-eugene** [comment]
I had to add library path to babelInclude

got hint from 

https://react-native-elements.github.io/react-native-elements/docs/web_usage.html

**Comment by sandro768** [comment]
In my case I had to correct sequence. First goes addBabelPresets and then babelInclude.

**Comment by spiderworm** [comment]
@littlehome-eugene @sandro768  If you have @babel/plugin-proposal-class-properties and/or @babel/plugin-proposal-private-methods working with CRA, I would love to see your full config-overrides.js file
