### ISSUE TITLE
How to injectManifest into adjustWorkbox

### ISSUE THREAD

**Issue by dandro32** [arackaf/customize-cra#24]
Is there posibility to injectManifest with new workbox configuration (runtimeCaching routs etc.)?
Thanks.

**Comment by arackaf** [comment]
Use the `adjustWorkbox` plugin, and add whatever settings you want.  ie

```js
adjustWorkbox(wb => Object.assign(wb, { skipWaiting: true, exclude: (wb.exclude || []).concat("index.html") }))
```
