### ISSUE TITLE
'sourceMap' seems to replace ‘source’

### ISSUE THREAD

**Issue by T-Inphic** [arackaf/customize-cra#248]
{
        loader: require.resolve("less-loader"),
        options: Object.assign(loaderOptions, {
          source: shouldUseSourceMap
        })
}

**Comment by Anish-Agnihotri** [comment]
Hi @T-Inphic,

This issue has been resolved in the latest `customize-cra` at version `1.0`. It is a breaking change, and you can follow the migration guide in #253 to fix the issue you were running into (you have to nest your configuration in the `lessOptions` object.
