### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by junhwong** [arackaf/customize-cra#251]
Is this project dead? I haven't seen an update in about 1 year.
Please tell me what you know, thanks!

**Comment by Anish-Agnihotri** [comment]
Hi @junhwong,

I've just received repo moderator and NPM publishing access from Adam for this repository, and will be working to catch-up on the all the open issues and PRs this week.

Will keep you in the loop and keep this issue open so that individuals are aware.

**Comment by junhwong** [comment]
Looking forward to doing better and thanks for your contribution
