### ISSUE TITLE
Can't define multiple paths alias in typescript ?

### ISSUE THREAD

**Issue by arpitprod** [arackaf/customize-cra#268]
I'm moving my codebase javascript to typescript. It was working with javascript code but not working with typescript code and I want to use multiple alias. This is my code 

> const { override, addWebpackAlias } = require('customize-cra');
const path = require('path');
const resolve = (dir) => path.resolve(__dirname, dir);
module.exports = override(
  addWebpackAlias({
    "Components": resolve('./src/ui/components'),
    "Pages": resolve('./src/ui/pages'),
    "Theme": resolve('./src/ui/theme.js'),
    "Api": resolve('./src/core/api'),
    "Hooks": resolve('./src/core/hooks'),
    "Utils": resolve('./src/core/utils'),
  })
);

but it's showing error
`Module not found: Can't resolve 'Theme' in '/Users/abc/Documents/pro/src'`

These are related versions

> "customize-cra": "^1.0.0",
"react": "^16.13.1",
"react-app-rewired": "^2.1.6",
"react-dom": "^16.13.1",
"react-scripts": "^3.4.3",
"typescript": "^4.0.2",

Please tell what I'm doing wrong

**Comment by the-simian** [comment]
references: https://github.com/arackaf/customize-cra/issues/207

**Comment by arpitprod** [comment]
sorry, it was silly mistake from my side only.
theme filename is `theme.ts` and I'm writing `theme.js` in script.
`"Theme": resolve('./src/ui/theme.js'),`
So, It's showing error `Module not found: Can't resolve 'Theme' in '/Users/abc/Documents/pro/src'`
