### ISSUE TITLE
Cannot upgrade to autoprefixer 10 | postcss 8 | postcss-loader 4

### ISSUE THREAD

**Issue by anhtran** [arackaf/customize-cra#273]
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.

 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }

**Comment by bondiano** [comment]
I have written the script to fix errors with the newest postcss
```javascript
const fixPostCSS = () => config => {
  config.module.rules[1].oneOf.forEach(rule => {
    rule.use?.forEach(item => {
      if (typeof item === 'string') {
        return;
      }

      const postCSSLoaderPath = require.resolve('postcss-loader');

      if (item.loader === postCSSLoaderPath) {
        item.options.postcssOptions = { plugins: item.options.plugins() };
        delete item.options.plugins;
        delete item.options.ident;
      }
    });
  });
  return config;
};
```
Maybe it will be useful

**Comment by fameoflight** [comment]
@bondiano how do you use this script? Sorry if this is a noob question

**Comment by fameoflight** [comment]
I was able to make it work, for anyone else who stumble here, here are few changes I needed to make 

```javascript
const { fixBabelImports, addLessLoader, useBabelRc, override } = require("customize-cra");

const fixPostCSS = () => config => {
  config.module.rules[1].oneOf.forEach(rule => {
    rule.use?.forEach(item => {
      if (typeof item === 'string') {
        return;
      }

      const postCSSLoaderPath = require.resolve('postcss-loader');

      if (item.loader === postCSSLoaderPath) {
        console.log(item);
        if ('options' in item) {
          item.options.postcssOptions = { plugins: item.options.plugins };
          delete item.options.plugins;
          delete item.options.ident;
        }

      }
    });
  });
  return config;
};

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
    style: false
  }),
  useBabelRc(),
  addLessLoader({
    sourceMap: true,
    lessOptions: {
      modifyVars: {
        "@primary-color": "#1DA57A", // for example, you use Ant Design to change theme color.
      },
      javascriptEnabled: true,
    }
  }),
  fixPostCSS()
);
```

**Comment by Shin1122** [comment]
> I was able to make it work, for anyone else who stumble here, here are few changes I needed to make
> 
> ```js
> const { fixBabelImports, addLessLoader, useBabelRc, override } = require("customize-cra");
> 
> const fixPostCSS = () => config => {
>   config.module.rules[1].oneOf.forEach(rule => {
>     rule.use?.forEach(item => {
>       if (typeof item === 'string') {
>         return;
>       }
> 
>       const postCSSLoaderPath = require.resolve('postcss-loader');
> 
>       if (item.loader === postCSSLoaderPath) {
>         console.log(item);
>         if ('options' in item) {
>           item.options.postcssOptions = { plugins: item.options.plugins };
>           delete item.options.plugins;
>           delete item.options.ident;
>         }
> 
>       }
>     });
>   });
>   return config;
> };
> 
> module.exports = override(
>   fixBabelImports("import", {
>     libraryName: "antd",
>     libraryDirectory: "es",
>     style: false
>   }),
>   useBabelRc(),
>   addLessLoader({
>     sourceMap: true,
>     lessOptions: {
>       modifyVars: {
>         "@primary-color": "#1DA57A", // for example, you use Ant Design to change theme color.
>       },
>       javascriptEnabled: true,
>     }
>   }),
>   fixPostCSS()
> );
> ```

nice ~！
