### ISSUE TITLE
Compatibility with React 17 / react-scripts 4.0.0

### ISSUE THREAD

**Issue by kenbanks-peng** [arackaf/customize-cra#274]
Does anyone have any insight into potential support for react-scripts 4.0.0 ? Thank you.

I hit a react-app-rewired error when trying to use customize-cra @ 1.0.0 / react-app-rewired @ 2.16 with React 17 / react-scripts@4.0.0

The error does not occur with React 16 and react-scripts 3.

Cannot read property 'use' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! start: react-app-rewired start
npm ERR! Exit status 1

**Comment by jeggy** [comment]
This happens because of CRA switched to [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin). 

But reading through the release notes, they say this: 
> as it is no longer required to customize the ESLint config.

So to fix this, you just need to remove the `useEslintRc` from your `config-overrides.js`. It should still be using your eslintrc file :smiley:

**Comment by kenbanks-peng** [comment]
Thank you @jeggy. I removed useEslintRc and the error went away. Maybe some documentation could be added to highlight useEslintRc is not to be used with react-scripts 4.

**Comment by trsp400** [comment]
> This happens because of CRA switched to [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin).
> 
> But reading through the release notes, they say this:
> 
> > as it is no longer required to customize the ESLint config.
> 
> So to fix this, you just need to remove the `useEslintRc` from your `config-overrides.js`. It should still be using your eslintrc file smiley

Thank you! It works for me
