### ISSUE TITLE
how to enable less-loader to process .less file? like use 'react-app-rewire-less'?

### ISSUE THREAD

**Issue by pengqin33** [arackaf/customize-cra#28]

**Comment by arackaf** [comment]
You’ll need to send a PR modifying the webpack config to add a less loader - sorry, I’ve never used LESS before - not sure what that’d look like.

**Comment by pengqin33** [comment]
like this can work! 
`const {
  override,
  addDecoratorsLegacy,
  useBabelRc,
  disableEsLint
} = require("customize-cra");

const rewireLess = require('react-app-rewire-less')
const theme = require('./package.json').theme

const lessLoader = (loaderOptions) => (config, env) => {
  config = rewireLess.withLoaderOptions(loaderOptions)(config, env)
  return config
}

module.exports = override(
  addDecoratorsLegacy(),
  disableEsLint(),
  useBabelRc(),
  lessLoader({
    modifyVars: theme,
    javascriptEnabled: true
  })
);`

**Comment by arackaf** [comment]
Are you asking or telling me that that’ll work? If asking, no idea. If that does in fact work, then shoot me a PR and I’ll get it added!

**Comment by DriesVandermeulen** [comment]
🔫 It just works  

```javascript
let modifiedConfig = addBabelPlugin(styledJsx)(config)
modifiedConfig = addBabelPlugin(antd)(modifiedConfig)
modifiedConfig = rewiredLess.withLoaderOptions(lessLoaderOptions)(modifiedConfig, env)
return modifiedConfig
```
