### ISSUE TITLE
disableEslint doesn't seem to have effect on react-scripts@4

### ISSUE THREAD

**Issue by layerssss** [arackaf/customize-cra#282]
Hi team,

After upgrading to react-scripts@4 (from 3.x), `disableEslint` seems to no longer having any effects. Both the `react-app-rewired start` process and browser console start to throw eslint warnings and errors. I'm not sure whether this should be a `customize-cra` or `react-app-rewired` issue though, so trying open it here first.

I have made a minimum example to reproduce this: https://github.com/layerssss/cra4-customize-issue

Expect result: the `yarn start` process and browser console should NOT have the `no-unused-vars` warning
Actual: the warning is present.

**Comment by Menci** [comment]
This is fixed in #278.
