### ISSUE TITLE
ESlint on Typescript files

### ISSUE THREAD

**Issue by samuelcastro** [arackaf/customize-cra#33]
I know that there is an option to enable eslint on ts|tsx files, I'm wondering whether I still need to include [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser) or you're using it already under the hood.

Thanks

**Comment by dalcib** [comment]
In my tests on thi, I also had to install `typescript-eslint-parser` and  `eslint-plugin-typescript`, to configure `useEslintRc` in customize-cra, and to use this .eslintrc:

```
{
  "parser": "typescript-eslint-parser",
  "extends": "react-app",
  "plugins": ["typescript"],
}
```

It also works with Eslint extension in Vscode.
