### ISSUE TITLE
Not working with Ant Design (babel-plugin-import)

### ISSUE THREAD

**Issue by samuelcastro** [arackaf/customize-cra#35]
This is my config:

```
module.exports = override(
  fixBabelImports('antd', {
    libraryName: 'antd',
    style: true
  }),
  useEslintRc(),
  enableEslintTypescript()
);
```

And for some reason this is not working.

I'm using CRA 2.x with typescript, `react-app-rewired` and `babel-plugin-import` are installed properly.

Any thoughts?

**Comment by samuelcastro** [comment]
closing, not an issue here.

**Comment by joao-alberto** [comment]
@samuelcastro Did you solved the problem? How?

**Comment by phungrk** [comment]
@joao-alberto 
Here the solution !
https://github.com/timarney/react-app-rewired/issues/348
