### ISSUE TITLE
addBundleVisualizer open a new tag each time

### ISSUE THREAD

**Issue by solayao** [arackaf/customize-cra#37]
```
if (module.hot) {
    module
        .hot
        .accept()
}
```
when i hot load cra,  the func addBundleVisualizer() create a new tag for analyzing every time when i changed.
if i use addBundleVisualizer({}, true), the react-router can't apply to visit the report.html.
how i use addBundleVisualizer and the analyze page open once??

**Comment by FezVrasta** [comment]
the report is not meant to be used in your app 🤔
