### ISSUE TITLE
[QUESTION] How setup proxy on dev server

### ISSUE THREAD

**Issue by akaguny** [arackaf/customize-cra#40]
In documentation i see:
```
  webpack: override(
    // usual webpack plugin
    disableEsLint()
  ),
  devServer: overrideDevServer(
    // dev server plugin
    watchAll()
  )
```
is `// dev server plugin` any javascript code?
in my case i want to use http-proxy-middleware package described in https://webpack.js.org/configuration/dev-server/#devserver-proxy

**Comment by arackaf** [comment]
No - you'd need to make a plugin for *this* project that modified the webpack config object to start using that middleware package.

**Comment by akaguny** [comment]
Thnks!
If i think correctry now in project only one plugin and it `watchAll`?

**Comment by arackaf** [comment]
Sorry not sure - I don't use webpack-dev-server

**Comment by sylvainDNS** [comment]
You can do it easily like this : 
```js
// config-overrides.js

const { overrideDevServer } = require('customize-cra')

const addProxy = proxy => config => {
  config.proxy = proxy
  return config
}

module.exports = {
  devServer: overrideDevServer(
    addProxy({
      '/v2': {
        target: 'http://localhost:3000',
        pathRewrite: { '^/v2': '' },
      },
    })
  ),
}

```
