### ISSUE TITLE
react-app-rewire-define-plugin

### ISSUE THREAD

**Issue by saostad** [arackaf/customize-cra#44]
Hi,

is there any way to define environment variable in webpack config?
something like : 
```
const rewireDefinePlugin = require('react-app-rewire-define-plugin')

// Use `webpack.DefinePlugin` to add the version number from package.json
config = rewireDefinePlugin(config, env, {
  'process.env.VERSION': JSON.stringify(require('./package.json').version)
})
```

**Comment by aaronchenwei** [comment]
Here is what we tried to rewire process.env

```js

const findWebpackPlugin = (plugins, pluginName) =>
  plugins.find(plugin => plugin.constructor.name === pluginName);

const overrideProcessEnv = value => config => {
  const plugin = findWebpackPlugin(config.plugins, 'DefinePlugin');
  const processEnv = plugin.definitions['process.env'] || {};

  plugin.definitions['process.env'] = {
    ...processEnv,
    ...value,
  };

  return config;
};

module.exports = override(
  overrideProcessEnv({
    VERSION: JSON.stringify(require('./package.json').version),
  })
);
```

**Comment by FezVrasta** [comment]
Just wondering, does the variables set into the `.env` get consumed by webpack as well? If so maybe we can leverage dotenv to inject the variables in a clean way

**Comment by aaronchenwei** [comment]
dotenv in CRA requires environment variables starting with `REACT_APP_` except `NODE_ENV`. That is why we want directly access `DefinePlugin`.

**Comment by devals9** [comment]
@aaronchenwei 
I would like to be able to use DefinePlugin to define __DEV__ and __PROD__ variables. Any idea how I should try to achieve that ? I tried your solution but it does not work.

**Comment by aaronchenwei** [comment]
@devals9 

Do you mean ?
```js
proccess.env.DEV = {...}
process.env.PROD = {...}
```
My previous code snippet is just to append variables under `process.env`

**Comment by huxianghe** [comment]
Here is package.json/scritps config:
`
  "scripts": {
    "dev": "react-app-rewired start --open",
    "build:test": "react-app-rewired build --test",
    "build:pre": "react-app-rewired build --pre",
    "build:prod": "react-app-rewired build --prod",
    "eject": "react-scripts eject"
  }
`

const path = require('path')
const path = require('path')
const Dotenv = require('dotenv-webpack')
const version = JSON.stringify(require('../package.json').version)

const resolvePath = dir => path.join(__dirname, '..', dir)

const mode = process.argv[2].split('--')
const isDev = process.env.NODE_ENV === 'development'

const envPath = isDev ? resolvePath('.env.development') : resolvePath(`.env.${mode}`)
const envVars = {}

const definitions = new Dotenv({
    path: envPath
}).definitions

Object.keys(definitions).forEach(key => {
  const [, api] = key.split('process.env.')
  envVars[api] = definitions[key]
})

function rewireDefinePlugin (config) {
  config.plugins.some(p => {
    if (
      p.definitions &&
      p.definitions['process.env']
    ) {
      p.definitions['process.env'] = { ...envVars, version}
      return true
    }
  })
  return config
}

module.exports = rewireDefinePlugin

**Comment by with-heart** [comment]
Closing as the solution from @aaronchenwei is verified as working with `customize-cra@0.6.3`+. If there are further problems, please open a new issue.

**Comment by foxundermoon** [comment]
https://github.com/foxundermoon/cra-define-override#readme
