### ISSUE TITLE
export getBabelLoader 

### ISSUE THREAD

**Issue by PinkaminaDianePie** [arackaf/customize-cra#47]
Please export `getBabelLoader` as well :)

**Comment by arackaf** [comment]
Sorry what?  Need a lot more context here

**Comment by arackaf** [comment]
Oh I see what you mean - not sure when I'll get to that - PRs welcome though

**Comment by arackaf** [comment]
My bad sorry - will get it out today!

**Comment by arackaf** [comment]
Done
