### ISSUE TITLE
addLessLoader css-loader modules

### ISSUE THREAD

**Issue by m-weeks** [arackaf/customize-cra#50]
addLessLoader works perfectly as intended to use LESS in the project; however it would be nice to use less css modules. I see it is already chaining style-loader and css-loader, but in order to use modules you need to give css-loader the option `modules: true`. This is not possible in the current setup.

I could see others possible wanting to pass other options to css-loader as well, like `sourceMap` or `localIdentName`.

**Comment by arackaf** [comment]
I'm not familiar with LESS, but this sounds like a great change.  PRs open if you're up for it

**Comment by yangmiao7** [comment]
I also have this problem.

**Comment by arackaf** [comment]
I think someone may have added this feature already.  Check the docs (and code). If not, PR's are still open ...
