### ISSUE TITLE
How can I set unique name for babel@7 with fixBabelImports ？

### ISSUE THREAD

**Issue by Terryand** [arackaf/customize-cra#52]
In Create-React-APP@2 and react-app-rewired
My config-overrides.js like this:

`config-overrides.js`
`const { override, fixBabelImports } = require('customize-cra');`
`module.exports = override(`
`   fixBabelImports('import', {`
`   libraryName: 'antd',`
`   libraryDirectory: 'es',`
`   style: 'css',`
` }),`
`  fixBabelImports('import', {`
`   libraryName: '@alifd/next',`
`   style: true,`
`   }),`
`);`

I try to read source code of fixBableImports,  but I have no idea at all

**Comment by Terryand** [comment]
> M

**Comment by Terryand** [comment]
Sorry, I know

**Comment by psudocode** [comment]
can you tell me how?
