### ISSUE TITLE
react-app-rewire-hot-loader

### ISSUE THREAD

**Issue by GloriaCHL** [arackaf/customize-cra#54]
Hi, how to config when I use [react-app-rewire-hot-loader](https://github.com/cdharris/react-app-rewire-hot-loader)? I tried, but didn't work:
```const {override, fixBabelImports, addWebpackAlias} = require('customize-cra');
const path = require('path');
const rewireReactHotLoader = require('react-app-rewire-hot-loader');

const fixedHot = value => config => {
  config = rewireReactHotLoader(config, process.env);
  return config;
};

module.exports = {
  webpack: override(
    fixBabelImports('import', {
      libraryName: 'antd',
      libraryDirectory: 'es',
      style: 'css',
    }),
    addWebpackAlias({
      ['@@']: path.resolve(__dirname, 'src/')
    }),
    fixedHot(),
  ),
  devServer: function(configFunction) {
    return function(proxy, allowedHost) {
      const config = configFunction(proxy, allowedHost);
      config.hot = true;
      return config;
    }
  }
};
```

**Comment by FezVrasta** [comment]
You may try to use the [`addBabelPlugin`](https://github.com/arackaf/customize-cra#addbabelpluginplugin) utility to add `react-hot-loader/babel` and see if it works.

**Comment by FezVrasta** [comment]
Alternatively, if you use Yarn, you may use `react-🔥-dom` without having to override any CRA config.

**Comment by FezVrasta** [comment]
@GloriaCHL have you sorted out your problem? Can we close this issue?

**Comment by alexkreidler** [comment]
any updates?

**Comment by MeetzhDing** [comment]
@GloriaCHL  @alexkreidler 

I get this solution, and it's work for me !

```js
const { override, fixBabelImports } = require('customize-cra');
const rewireReactHotLoader = require('react-app-rewire-hot-loader');

module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: 'css',
  }),
  (config, env) => {
    config = rewireReactHotLoader(config, env);
    return config;
  }
)
```

Other steps:  http://npm.taobao.org/package/react-app-rewire-hot-loader

**Comment by quannh25595** [comment]
I don't know why but the  `env` in @MeetzhDing  seems to be  `undefined`. And I found `mode` inside `config`. This code works for me

`
const { override, fixBabelImports } = require('customize-cra');
const rewireReactHotLoader = require('react-app-rewire-hot-loader');

/* config-overrides.js */
module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: 'css',
  }),
  config => {
    if (config.mode === 'development') {
      config.resolve.alias['react-dom'] = '@hot-loader/react-dom';
    }
    config = rewireReactHotLoader(config, config.mode);
    return config;
  },
);
`

**Comment by SylvanasGone** [comment]
I implemented a plugin which will let you use hot-loader directly without extra code
```js
const { override } = require('customize-cra')
const rewireReactHotLoader = require('react-app-rewire-hot-loader-for-customize-cra')

module.exports = override(
  // ...other rewires
  rewireReactHotLoader()
)
```
https://www.npmjs.com/package/react-app-rewire-hot-loader-for-customize-cra

have a try

**Comment by liuxinqiong** [comment]
@quannh25595 It worked for me，thanks for your share

**Comment by SteffeyDev** [comment]
I got it working just by putting the function in directly:
```
const rewireReactHotLoader = require('react-app-rewire-hot-loader');

module.exports = override(
  rewireReactHotLoader,
  ...otherOptions
}
```

Conceptually, this is equivalent to @MeetzhDing's solution, just simplified to it's fullest extent.
