### ISSUE TITLE
How to add any plugin?

### ISSUE THREAD

**Issue by apfz** [arackaf/customize-cra#58]
Hi, great tool!

Could you explain to me how I can override or add to the original Webpack config?

I would like to add the following plugin to Webpack:

https://www.npmjs.com/package/bless-css-webpack-plugin#usage

Thanks!

**Comment by bfischer1121** [comment]
If you pass a function to override, customize-cra will call it with the webpack config object, like so:
```javascript
const MyPlugin = require('myplugin')

const addMyPlugin = config => {
  config.plugins.push(new MyPlugin())
  return config
}

module.exports = override(
  addMyPlugin,
  ...
)
```

**Comment by Murphycx94** [comment]
> If you pass a function to override, customize-cra will call it with the webpack config object, like so:
> 
> ```js
> const MyPlugin = require('myplugin')
> 
> const addMyPlugin = config => {
>   config.plugins.push(new MyPlugin())
>   return config
> }
> 
> module.exports = override(
>   addMyPlugin,
>   ...
> )
> ```

``` javascript
const {
  addLessLoader,
  fixBabelImports,
  override
} = require("customize-cra");

const { DefinePlugin } = require('webpack');

function addPlugin(config) {
  console.log(config)
  // config.plugins.push(new DefinePlugin(JSON.stringify({ TEST: process.env.TEST })));
  return config;
}

module.exports = {
  webpack: override(
    addLessLoader({
      javascriptEnabled: true
    }),
    fixBabelImports("babel-plugin-import", {
      libraryName: "antd-mobile",
      style: true
    }),
    addPlugin()
  )
};
```
my config is undefined
why?

**Comment by zhoucumt** [comment]
if I use like this:
module.exports = {
    webpack: override(
        // do sth
   ),
   devServer: (configFunction) => {
    }
};
how do I add uglifyjs-webpack-plugin? 
@arackaf @bfischer1121

**Comment by with-heart** [comment]
@zhoucumt Were you able to answer your own question?
