### ISSUE TITLE
Using babelInclude("node_modules/shared-lib") doesn't seem to work

### ISSUE THREAD

**Issue by doronoded** [arackaf/customize-cra#61]
In my shared-lib, I have a file that uses class properties that should be compiled by babel like the example below: 
```
class Shared-utils {
    someProp = () => {
        //do stuff
    }

export default Shared-utils
```

When I run npm start in my main project I get the following error:
```
SyntaxError: path-to-shared-lib/Shared-utiles.js: Support for the experimental syntax 'classProperties' isn't currently enabled (8:9):
...
Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

**Comment by doronoded** [comment]
Could it be because shared-lib is a local folder with a symlink?

**Comment by doronoded** [comment]
Yes, its because its a seemlink!
Any suggestions?

**Comment by andre-engelbrecht** [comment]
Same problem. I'm adding a path to a symlink and it does not seem to get transpiled.

**config-override.js:**
```
const { override, babelInclude } = require("customize-cra");
const path = require("path");

module.exports = override(
  babelInclude([
    path.resolve("src"), // make sure you link your own source
    path.resolve("../../node_modules/@project/comp-one")
  ])
);
```

Error:
```
...\comp-one\src\index.js: Unexpected token (3:22)

  1 | import React from 'react';
  2 | 
> 3 | const CompOne = () => <div>
    |                       ^
  4 |     <h3>CompOne</h3>
  5 |     <p><i>Transpiled On-The-Fly</i></p>
```

Help would be appreciated!

**Comment by FezVrasta** [comment]
May you try with `removeModuleScopePlugin()`? I'm not sure it will help but it's worth a shot.

**Comment by andre-engelbrecht** [comment]
Hi, I tried all of the options below: 

```
const {
  override,
  overrideDevServer,
  disableEsLint,
  watchAll,
  removeModuleScopePlugin
} = require("customize-cra");

module.exports = {
  // webpack: override(
  //   removeModuleScopePlugin,
  //   watchAll()
  // ),
  // devServer: overrideDevServer(
  //   removeModuleScopePlugin,
  //   watchAll()
  // )
  removeModuleScopePlugin
};
```
Still get the same issue, code is not transpiled. If I manually transpile with babel it works, so I know that's the problem.

**Comment by doronoded** [comment]
Hey, I figured it out..
You can use 
`fs.realpathSync("../../node_modules/@project/comp-one")`
instead of
`path.resolve("../../node_modules/@project/comp-one")`

It solved my problem.

**Comment by andre-engelbrecht** [comment]
YES, it works. Thanks @doronoded !

**Comment by doronoded** [comment]
wrote a blog post about this:
https://medium.com/capriza-engineering/sharing-source-code-and-libraries-in-react-bd30926df312
