### ISSUE TITLE
How can I config overrideDevServer?

### ISSUE THREAD

**Issue by amazingzcj** [arackaf/customize-cra#62]
I want to reset historyApiFallback，but I can not do it

it looks like
devServer: overrideDevServer(
     xxxxxxxxxxxxxxxxxx
 )

**Comment by ElsaOOo** [comment]
![image](https://user-images.githubusercontent.com/48074435/54803375-35117a80-4caa-11e9-9233-f34d442bf235.png)

it needs a function, so return a function.

**Comment by amazingzcj** [comment]
oh nice~! thanks very much! return a function and then it works.

**Comment by casamia918** [comment]
Please add above image into README
