### ISSUE TITLE
How to add a webpack loader

### ISSUE THREAD

**Issue by mcanobbio** [arackaf/customize-cra#64]
Is there a way to add a loader with some webpack configuration like this?https://ant.design/components/icon/#Custom-SVG-Icon 

I found this example https://github.com/gitim/react-app-rewire-svgr/blob/master/index.js but I cannot make it works

**Comment by myzhoulang** [comment]
@mcanobbio 可以这样配置

![image](https://user-images.githubusercontent.com/7009272/58416769-3f3e6380-80b5-11e9-9a74-c0dd32c451de.png)

**Comment by ArkeaOpenbanking** [comment]
I'm facing the same problem with html-loader, i need to do this :
![image](https://user-images.githubusercontent.com/50942677/58537106-80885d80-81f2-11e9-8c23-89945e6b711b.png)
But I don't know how to insert this code inside my config-override.js

**Comment by Next0186** [comment]
> loader

![image](https://user-images.githubusercontent.com/44919719/58801671-c9e70b80-863d-11e9-9d7d-a5f83012ae6f.png)

**Comment by davidsonsns** [comment]
About SVG only for remember, in `>= react-scripts@2.0.0` you can import svg direclty. See [Adding SVGs](https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files#adding-svgs)

**Comment by jpcmf** [comment]
@davidsonsns how about SVG Sprites?

**Comment by the-simian** [comment]
I added a PR that makes SVG manipulation a lot easier and is relevant to this thread: https://github.com/arackaf/customize-cra/pull/271

If that gets pulled all you need to do is just include the convenience function  like 
```
override(
  enableSVGO()
 //....
);
```
