### ISSUE TITLE
Add the option to customize the "stats" attribute

### ISSUE THREAD

**Issue by danilofuchs** [arackaf/customize-cra#67]
There should be an option to customize webpack's `stats` attribute.
[To solve this issue on mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250), it is required to change the property.

**Comment by with-heart** [comment]
Hi @danilofuchs, is this still an issue for you? Have you found a workaround or created your own function for handling this change?

**Comment by danilofuchs** [comment]
As I'm currently using Styled Components, not Sass, I haven't faced this issue in some time. But to my understanding, this is still a major issue for Sass users, but a simple customize-cra function is viable to those still needing to fix this.

**Comment by danilofuchs** [comment]
If you think this is out of the scope of this project, I'm happy to close the issue and propose a user-made solution

**Comment by with-heart** [comment]
I'm fine with that being added, if anyone would like to open a PR.

**Comment by danilofuchs** [comment]
I'll work on it!

**Comment by with-heart** [comment]
Thank you! Sorry for taking so long to say that 😆 looking forward to it!

**Comment by danilofuchs** [comment]
I have been working on it, but I can't seem to make create-react-app respect the config. I think their implementation of error / warning handling is overriding webpack's actions.
