### ISSUE TITLE
Question: Exclude

### ISSUE THREAD

**Issue by eluchsinger** [arackaf/customize-cra#68]
I ran into a problem while trying to exclude some file extensions. How can I exclude all files ending with `.config`, `.overrides` or `.variables`?

I tried following, but apparently it didn't work:

```javascript
adjustWorkbox(wb =>
        Object.assign(wb, {
            skipWaiting: true,
            exclude: (wb.exclude || [/\.(config|overrides|variables)$/]).concat("index.html")
        }))
```

More context:
https://stackoverflow.com/a/48608002/2632991  
and  
https://github.com/Semantic-Org/Semantic-UI-LESS/issues/37

**Comment by arackaf** [comment]
Exclude those extensions from *what*? `adjustWorkbox` is for changing the Workbox confiruation, and I don't think Workbox uses an `exclude` value.

**Comment by geminiyellow** [comment]
hi @arackaf , how to add babel Exclude path?

**Comment by with-heart** [comment]
@eluchsinger Similar to @arackaf, I'm not sure what you're asking for here. The `exclude` in the linked SO topic is from `file-loader`, and we don't currently offer a way to modify loader configurations. You could create your own function that does that though.

@geminiyellow We currently don't have a way to do that, but I've opened #110 to address that.

Closing this issue.
