### ISSUE TITLE
Cannot find module 'react-scripts/config/paths'

### ISSUE THREAD

**Issue by vegawong** [arackaf/customize-cra#71]
https://github.com/arackaf/customize-cra/blob/d000b481201b3df0e58260394aa4d50b2adef2e9/index.js#L172

I found the module refrence here. If i use a custom react-scripts version , it would crash with this report.

**Comment by vegawong** [comment]
hey guys!  Has anything made？

**Comment by with-heart** [comment]
This issue is difficult to handle because we have no way of knowing the `paths` location for every custom `react-scripts` implementation, and there's no way to automatically detect the name of the custom module either. However, since [`react-app-rewired`](https://github.com/timarney/react-app-rewired#2-custom-scripts-versions) supports custom scripts versions, I think we should too.

See #103

**Comment by vegawong** [comment]
@with-heart Thank you for your reply! I remember `react-app-rewired` as if we were using `.env` file  to record custom scripts versions, and I thought we could follow suit and use it better with react-app-rewired.

**Comment by with-heart** [comment]
That's certainly something you could store in `.env` and read in `config-overrides.js` to modify how you override configs, but as far as I'm aware, it's never been something done automatically in `react-app-rewired`. 

As part of #103, I will add a way to inject custom `paths` to support what you'd like to do here. I'm going to close this issue, so follow along there for updates :)

**Comment by with-heart** [comment]
@vegawong You were correct, that should be supported through the `REACT_SCRIPTS_VERSION` var or the `--scripts-version` command line option ([documented here](https://github.com/timarney/react-app-rewired#2-custom-scripts-versions)). That'll be factored into #103.

**Comment by siddharth-golchha** [comment]
@vegawong Is there a workaround for this use case? I am facing this same issue where I am using custom react-scripts version and getting the same issue.

**Comment by vegawong** [comment]
> @vegawong Is there a workaround for this use case? I am facing this same issue where I am using custom react-scripts version and getting the same issue.

haha！ I just simply copy the problematic api code into a separate js file to modify and replace the api that is imported directly using from the package.
