### ISSUE TITLE
getBabelLoader breaks when not using oneOf

### ISSUE THREAD

**Issue by mschipperheyn** [arackaf/customize-cra#76]
`getBabelLoader` has a fallback when `babel-loader` is not found using oneOf. Unfortunately, a `oneOf` itself is required, because it bombs here https://github.com/arackaf/customize-cra/blob/c088d018657cb362472ec885ddbac270beb3814b/index.js#L35 when you have a simple `use` array

**Comment by with-heart** [comment]
Hi @mschipperheyn, is this still an issue for you?

**Comment by mschipperheyn** [comment]
@with-heart I worked around it.
