### ISSUE TITLE
Adding presets? (typescript)

### ISSUE THREAD

**Issue by jadbox** [arackaf/customize-cra#8]
I'm looking into how I can get Typescript to work with CRA 2.0. It seems like with Babel 7 that typescript support is enabled by setting a preset rather than just adding a plugin (see the below snippet). Any recommendations on what to do here?

https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/
```
Make sure your .babelrc has the right presets and plugins:

{
    "presets": [
        "@babel/env",
        "@babel/preset-typescript"
    ],
    "plugins": [
        "@babel/proposal-class-properties",
        "@babel/proposal-object-rest-spread"
    ]
}
```

**Comment by arackaf** [comment]
I'm afraid I'm not familiar with Babel 7, or how it integrates with TypeScript. Moreover, TypeScript support is coming soon to CRA, (from what @gaearon has said publicly on Twitter), so I'm not sure rushing into adding it here will be all that productive.

**Comment by arackaf** [comment]
I'm closing this, but if you really need TS now, feel free to figure out how to do it, and open a PR.  I'd be happy to merge it.

**Comment by jadbox** [comment]
@arackaf to address your original question, the PR for CRA2 support is pretty limited and won't even do type checking. I'm just looking for how I add babel presets using customize-cra.

**Comment by arackaf** [comment]
@jadbox there's no way to add a preset with customize-cra BUT it should be easy to add.  If you check out the addBabelPlugin method, it should be straightforward to copy that and modify for presets—bonus if you refactor the common code for finding the babel config, out.

PRs open!
