### ISSUE TITLE
Import additional plugins

### ISSUE THREAD

**Issue by Raycoms** [arackaf/customize-cra#80]
I just recently updated my dependencies but couldn't find any way to continue using my compression plugins together with customize-cra.

I got the following three plugins:

![image](https://user-images.githubusercontent.com/6438347/56039900-abcef000-5d0b-11e9-8491-e1e6200a8463.png)
![image](https://user-images.githubusercontent.com/6438347/56039825-9063e500-5d0b-11e9-9a5c-bffa88682932.png)

But I don't know how to include them with customize-cra.

I tried the ...addBabelPlugins but it doesn't work.

Is there any way to do this with customize-cra yet? Else I gotta stay on the older versions of cra and react-app-rewired unfortunately.

**Comment by Raycoms** [comment]
I tried it like this:

![image](https://user-images.githubusercontent.com/6438347/56039999-dae56180-5d0b-11e9-9593-d050afaa9b12.png)

Like this:

![image](https://user-images.githubusercontent.com/6438347/56040029-e8025080-5d0b-11e9-93de-3469ae985cf6.png)

Like this:

![image](https://user-images.githubusercontent.com/6438347/56040046-f2244f00-5d0b-11e9-8a83-e5351104a36c.png)

and even like this:

![image](https://user-images.githubusercontent.com/6438347/56040077-02d4c500-5d0c-11e9-8fdf-4508b5b12439.png)



But it doesn't work.

**Comment by arackaf** [comment]
That won’t work - you can’t add actual webpack plugin instances. You’re modifying the webpack config object, here. 

Check out the code (or customize-cra) to see how that works.

**Comment by Raycoms** [comment]
Is there any method or doc you could point me to, to find out how I am able to integrate those plugins?

**Comment by Raycoms** [comment]
The way it was done before when compose and injectBabelPlugin were still supported is not possible anymore and I couldn't find any documentation showing how to do it now.

**Comment by arackaf** [comment]
Look at how other plugins are implemented.

https://github.com/arackaf/customize-cra/blob/master/index.js
