### ISSUE TITLE
Customizing autoprefixer configuration

### ISSUE THREAD

**Issue by svencowart** [arackaf/customize-cra#81]
I would like to change the autoprefixer configuration to include `grid: 'autoplace'`.  Is there a way to do that with customize-cra?  I tried reloading autoprefixer as the following, but with no success:  `addPostcssPlugins([require('autoprefixer')({ grid: 'autoplace' })])`.

**Comment by with-heart** [comment]
@svencowart Were you able to get this working?

**Comment by svencowart** [comment]
No, I was unable to find a solution.

**Comment by with-heart** [comment]
This would probably require a function to [modify the existing postcss plugins](https://github.com/arackaf/customize-cra/blob/9a46d6ff4830fc817182024f376578f9d722b39a/src/customizers/webpack.js#L239-L258). You'd need to find the `autoprefixer` plugin that is created by `create-react-app` and modify its options. 

If anyone is interested in handling this, please open a PR.

**Comment by with-heart** [comment]
Once #172 is merged, this will be published as part of `v0.9`.
