### ISSUE TITLE
How do I get the packaging environment? dev or production

### ISSUE THREAD

**Issue by sunlili810** [arackaf/customize-cra#82]
I used process.env.BUNDLE_VISUALIZE == 1 && addBundleVisualizer(), It doesn't work.
I try process.env.NODE_ENV == 'production ' && new BundleAnalyzerPlugin(), and It doesn't work too.
How do I get the packaging environment?

**Comment by FezVrasta** [comment]
May you show an example of the code you are trying to write?

**Comment by sunlili810** [comment]
This is my config-overrides.js ：
const path = require('path');
const {
  override, fixBabelImports,addWebpackAlias,addBundleVisualizer
} = require('customize-cra');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true
  }),
  process.env.BUNDLE_VISUALIZE == 1 && addBundleVisualizer(),
  process.env.NODE_ENV == 'production ' && new BundleAnalyzerPlugin(),
 
  addWebpackAlias({
    components: path.join(__dirname, './src/components'),
  }),
);

and my packga

**Comment by sunlili810** [comment]
This is my config-overrides.js ：
const path = require('path');
const {
override, fixBabelImports,addWebpackAlias,addBundleVisualizer
} = require('customize-cra');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
module.exports = override(
fixBabelImports('import', {
libraryName: 'antd',
libraryDirectory: 'es',
style: true
}),
process.env.BUNDLE_VISUALIZE == 1 && addBundleVisualizer(),
process.env.NODE_ENV == 'production ' && new BundleAnalyzerPlugin(),

addWebpackAlias({
components: path.join(__dirname, './src/components'),
}),
);
and my packgage.json
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
  },

**Comment by FezVrasta** [comment]
You can't add plugins that way, you have to add them with the addBabelPlugin helper

https://github.com/arackaf/customize-cra#addbabelpluginplugin

**Comment by sunlili810** [comment]
I'm not going to add babel plugin，I'm  going to add webpack plugin，such as UglifyJsPlugin.
I want to know the webpack environment ，When i create an optimized production build if the webpack environment is 'production'  ，I will activate UglifyJsPlugin.

**Comment by FezVrasta** [comment]
Yeah right. Still that's not the right way. You have to add them to the plugins list. Not to there

**Comment by sunlili810** [comment]
![image](https://user-images.githubusercontent.com/30523306/56265532-6439d100-611c-11e9-8165-4b9bbddeeb31.png)
 It works in this way.
