### ISSUE TITLE
Question: Bundle size reduction

### ISSUE THREAD

**Issue by dtodt** [arackaf/customize-cra#83]
Greetings, I'm wonder if this alternative below is possible using `customize-cra`.

[two-quick-ways-to-reduce-react-apps-size-in-production](https://medium.com/@rajaraodv/two-quick-ways-to-reduce-react-apps-size-in-production-82226605771a)

I've tried to find a github repo with something like, but no success.

Thanks.

**Comment by FezVrasta** [comment]
These optimisations are provided out of the box by CRA, the only exception is the gzip at build time, you can add the plugin quite easily, just append it to the existing list of plugins.
