### ISSUE TITLE
Babel Plugin Emotion

### ISSUE THREAD

**Issue by arthurderyckere** [arackaf/customize-cra#86]
Is it possible to add the Emotion Plugin to the start of the Babel Plugin Array?

https://emotion.sh/docs/install#babelrc

**Comment by arackaf** [comment]
I'm sure it is. PR's welcome :)

**Comment by arthurderyckere** [comment]
`const addBabelPluginToStart = plugin => config => {
  getBabelLoader(config).options.plugins.unshift(plugin);
  return config;
};`
