### ISSUE TITLE
overrideDevServer does not work

### ISSUE THREAD

**Issue by Arichy** [arackaf/customize-cra#87]
here is the config-overrides.js (omitted require sentences)

```
const devServerConfig = () => config => {
    return {
        ...config,
        port: 3001
    }
}

module.exports = {
    webpack: override(
        fixBabelImports('import', {
            libraryName: 'antd',
            libraryDirectory: 'es',
            style: 'css'
        }),
        useBabelRc()
    ),

    devServer: overrideDevServer(devServerConfig())
}
```
But the port devServer uses is still 3000, not 3001

**Comment by crazyxhz** [comment]
use `PORT=3001 react-app-rewired start`

**Comment by Arichy** [comment]
> use `PORT=3001 react-app-rewired start`

This may work, but I want to customize webpack-dev-server，not only change the port. In fact, I want to add "changeOrigin" and so on.

**Comment by FezVrasta** [comment]
You may want to try to put a console.log in this line, and see if the original CRA config is logged.

https://github.com/arackaf/customize-cra/blob/master/index.js#L249

**Comment by Arichy** [comment]
> You may want to try to put a console.log in this line, and see if the original CRA config is logged.
> 
> https://github.com/arackaf/customize-cra/blob/master/index.js#L249

It's logged,and the updatedConfig has "port:3001" .But it still doesn't work.

**Comment by ElsaOOo** [comment]
here is my config file, it can proxy 3005 port while my frontend app is running at port 3000
``
const { 
  override, 
  fixBabelImports,
  overrideDevServer,
} = require('customize-cra');

const devServerConfig = () => config => {
  return {
      ...config,
      port: 3000,
      proxy: {
        '/app/v1': {
          target: 'http://localhost:3005',
          changeOrigin: true,
          ws: false,
          pathRewrite: {
            '^/app/v1': '/app/v1',
          },
          secure: false,
        },
      },
  }
}

module.exports = {
  webpack: override(
    fixBabelImports('import', {
      libraryName: 'antd',
      libraryDirectory: 'es',
      style: 'css',
    }),
  ),
  devServer: overrideDevServer(
    devServerConfig()
  )
}
``

**Comment by Arichy** [comment]
> here is my config file, it can proxy 3005 port while my frontend app is running at port 3000
> 
> ```js
> const { 
>   override, 
>   fixBabelImports,
>   overrideDevServer,
> } = require('customize-cra');
> 
> const devServerConfig = () => config => {
>   return {
>       ...config,
>       port: 3000,
>       proxy: {
>         '/app/v1': {
>           target: 'http://localhost:3005',
>           changeOrigin: true,
>           ws: false,
>           pathRewrite: {
>             '^/app/v1': '/app/v1',
>           },
>           secure: false,
>         },
>       },
>   }
> }
> 
> module.exports = {
>   webpack: override(
>     fixBabelImports('import', {
>       libraryName: 'antd',
>       libraryDirectory: 'es',
>       style: 'css',
>     }),
>   ),
>   devServer: overrideDevServer(
>     devServerConfig()
>   )
> }
> ```

The proxy works, but if the port is not 3000, the port still does not work. You can try to change port to 3001

**Comment by with-heart** [comment]
@Arichy were you ever able to resolve this issue?

**Comment by Arichy** [comment]
> @Arichy were you ever able to resolve this issue?

No, I give up and write webpack config by my self

**Comment by with-heart** [comment]
@Arichy Okay, good to know. I'll take a look and see if I can figure out the problem. Thanks!

**Comment by GoetheDady** [comment]
how to use it???notwork

**Comment by PursuitLife** [comment]
> > here is my config file, it can proxy 3005 port while my frontend app is running at port 3000
> > ```js
> > const { 
> >   override, 
> >   fixBabelImports,
> >   overrideDevServer,
> > } = require('customize-cra');
> > 
> > const devServerConfig = () => config => {
> >   return {
> >       ...config,
> >       port: 3000,
> >       proxy: {
> >         '/app/v1': {
> >           target: 'http://localhost:3005',
> >           changeOrigin: true,
> >           ws: false,
> >           pathRewrite: {
> >             '^/app/v1': '/app/v1',
> >           },
> >           secure: false,
> >         },
> >       },
> >   }
> > }
> > 
> > module.exports = {
> >   webpack: override(
> >     fixBabelImports('import', {
> >       libraryName: 'antd',
> >       libraryDirectory: 'es',
> >       style: 'css',
> >     }),
> >   ),
> >   devServer: overrideDevServer(
> >     devServerConfig()
> >   )
> > }
> > ```
> 
> The proxy works, but if the port is not 3000, the port still does not work. You can try to change port to 3001

What do you do in the end?

**Comment by junjie-lean** [comment]
overrideDevServer好像确实没有生效，我在我的config-overrides里设置webpack的dev-server配置，但是webpack的dev-server没有起作用。
你的dev-server生效了吗？ 我在更新了文件后，浏览器没有刷新。

**Comment by PursuitLife** [comment]
dev-server配置没有生效呢




------------------ 原始邮件 ------------------
发件人: "lean"<notifications@github.com>;
发送时间: 2019年9月6日(星期五) 下午2:02
收件人: "arackaf/customize-cra"<customize-cra@noreply.github.com>;
抄送: "其实有些话不 必多说"<826033056@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [arackaf/customize-cra] overrideDevServer does not work (#87)




overrideDevServer好像确实没有生效，我在我的config-overrides里设置webpack的dev-server配置，但是webpack的dev-server没有起作用。
 你的dev-server生效了吗？ 我在更新了文件后，浏览器没有刷新。

**Comment by with-heart** [comment]
`create-react-app` is hardwired to use `process.env.PORT` or the default of `3000`. There's nothing we can do to change that due to the way it's configured internally. [You can see that here.](https://github.com/facebook/create-react-app/blob/e7a2d6168a3a93ea58bafdc851eb2bbda20d5ce6/packages/react-scripts/scripts/start.js#L60)

**Comment by NewAwesome** [comment]
> `create-react-app` is hardwired to use `process.env.PORT` or the default of `3000`. There's nothing we can do to change that due to the way it's configured internally. [You can see that here.](https://github.com/facebook/create-react-app/blob/e7a2d6168a3a93ea58bafdc851eb2bbda20d5ce6/packages/react-scripts/scripts/start.js#L60)

i'm worried about the other devServer configs , can customise-cra override them indeedly ? Have you encountered any other problems ? i'm looking forward to ur reply ~

**Comment by theChengundertheQun** [comment]
And my config dosen't work too.
`
const addProxy = () => (config) => {
  return {
    ...config,
    port: 8000,
    proxy: {
      '/api': {
        target: 'http://47.114.4.244:18080',
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        },
        secure: false
      }
    }
  }
}

module.exports = {
  webpack: override(...), 
  devServer: overrideDevServer(
    addProxy()
  )
}`
Is there any problem? @with-heart

**Comment by theChengundertheQun** [comment]
> And my config dosen't work too.
> `
> const addProxy = () => (config) => {
> return {
> ...config,
> port: 8000,
> proxy: {
> '/api': {
> target: 'http://47.114.4.244:18080',
> changeOrigin: true,
> pathRewrite: {
> '^/api': ''
> },
> secure: false
> }
> }
> }
> }
> 
> module.exports = {
> webpack: override(...),
> devServer: overrideDevServer(
> addProxy()
> )
> }`
> Is there any problem? @with-heart

oh it is my bad..It is work

**Comment by coderwyd** [comment]
遇到同样问题，修改不了devServe的配置

**Comment by LwcReber** [comment]
如果本地有环境变量文件，看了react-script的代码，可以通过修改环境变量 process.env.PORT='8000', 端口就会改变

**Comment by BM-laoli** [comment]
遇到同样问题，修改不了devServe的配置

**Comment by erichow** [comment]
devServer 的参数都无法覆盖，不只是端口问题，其他参数也不能修改（other configs also does not work too~)
i'm worried about the other devServer configs , can customise-cra override them indeedly ?
