### ISSUE TITLE
How to add scss support to customize-cra ?

### ISSUE THREAD

**Issue by agarwalvinit** [arackaf/customize-cra#88]
I don't want to use less. I want to add scss support to my repo, but when I am adding the support I am getting following error.

**react-app-rewire-scss**
Error: The "getBabelLoader" helper has been deprecated as of v2.0. You can use customize-cra plugins in replacement - https://github.com/arackaf/customize-cra#available-plugins

**react-app-rewire-css-modules**
BrowserslistError: Unknown browser query `dead`

**Comment by FezVrasta** [comment]
Please read the documentation of the `addBabelPlugin` helper on our home page. Thanks.
