### ISSUE TITLE
How to add babel-plugin-transform-imports

### ISSUE THREAD

**Issue by frederikhors** [arackaf/customize-cra#89]
Can you explain how to use this: https://github.com/GoogleChromeLabs/webpack-libs-optimizations/blob/master/README.md#react-router in my `config-overrides.js`?

I need to use [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports) to strip unused modules:

```
// .babelrc
{
  "plugins": [
    ["transform-imports", {
      "react-router": {
        "transform": "react-router/${member}",
        "preventFullImport": true
      }
    }]
  ]
}
```

in:

```js
module.exports = override(
  ...addBabelPlugin('transform-imports')
);
```

**HOW TO**?

I'will PR the `Readme` file with your answer for newbies like me.

**Comment by frederikhors** [comment]
@FezVrasta, closing without answer?

**Comment by FezVrasta** [comment]
I see you provided an answer in your first post. Unfortunately we can't really provide all the possible examples in the README file, once we provide an `addBabelPlugin` utility anyone can use it to load whatever plugin they want.

**Comment by frederikhors** [comment]
Yes. You'right. What I don't understand is how to use the `addBabelPlugin`. So the question.

**Comment by FezVrasta** [comment]
You just have to pass the plugin configuration like you'd do in normal webpack.

module.exports = override(
  addBabelPlugin(["transform-imports", {
      "react-router": {
        "transform": "react-router/${member}",
        "preventFullImport": true
      }
    }])
);

**Comment by frederikhors** [comment]
Ok, thanks, but I have problem with this line:
```js
transform: 'react-router/${member}'
```

I think is not a valid javascript code.

If I use instead this one:

```js
transform: `react-router/${member}`
```

it complains about `member is not defined` of course.

I think I'm missing something. But what?
