### ISSUE TITLE
[Question] Specifying babel plugin configuration

### ISSUE THREAD

**Issue by sherwinyu** [arackaf/customize-cra#9]
Hi, I'm wondering how it would be possible to specify babel plugin configuration using the   `addBabelPlugin` API. I've read https://github.com/arackaf/customize-cra/blob/0c572088404dbbf48b5089479227f2cd410a5277/index.js#L21 but I'm not very clear on what it's doing.

Namely, I'm trying to get flow-runtime's babel plugin working https://codemix.github.io/flow-runtime/#/babel-plugin-flow-runtime with configuration.

Normally, I'd configure it with `.babelrc` by adding something like: 
```
{
  "presets": ["stage-2", "react"],
  "plugins": [
    "transform-decorators-legacy",
    ["flow-runtime", {
      "assert": true,
      "annotate": true,
      "optInOnly": true,
    }]
  ]
}
````
But `customize-cra` doesn't seem to be picking up the config.

Any help would be appreciated, and thanks for the work on this!

**Comment by arackaf** [comment]
CRA doesn't use the .babelrc file. I believe you'd want 

`addBabelPlugin(["flow-runtime"]);`

Basically, whatever you pass to `addBabelPlugin` will be passed to Babel's plugins array in the webpack config. Check Babel's docs for how to set that up.
