### ISSUE TITLE
How to add a css-loader support to cssmodules

### ISSUE THREAD

**Issue by The-Pursuit-of-Happyness** [arackaf/customize-cra#90]
I want to use css modules  like this ,but it's inoperative;

![image](https://user-images.githubusercontent.com/17919630/57452198-d02fd500-7295-11e9-8703-b7f8925fe512.png)

what should I do?

**Comment by FezVrasta** [comment]
Please use StackOverflow for this kind of questions, the team behind this project is small and we can't help everybody with their own personal issues.

Thank you for understanding!

**Comment by The-Pursuit-of-Happyness** [comment]
> Please use StackOverflow for this kind of questions, the team behind this project is small and we can't help everybody with their own personal issues.
> 
> Thank you for understanding!

Admittedly, I understand the size of your team and the current problem. I am not without the answer to this question. Since this plug-in is used to handle create-react-app and does not use eject, but customize-cra does most of the functions of webpack modules and plug-ins, why not add one to css? I looked at your source code before asking questions, and also looked at the related issues of the project. Some people have similar problems, but this is cssmodules. In my previous project, Ant Design Pro project, we can also add cssloader to deal with modularization while implementing this lessloader.

I raised this issue to solve the problem of the project. Although it's no problem not to use cssmodules at present, after all, cssmodules can't be used after adding Less Loader. We can't solve one problem and create another problem, can we?

Your attitude to answering questions makes me doubt your attitude and ability to solve problems.

There are many offences in presumption.

**Comment by The-Pursuit-of-Happyness** [comment]
I have solved this problem myself, but the reason for the problem is the problem of the plug-in library. The solution is as follows:

Modify the source code directly:

customize-cra/index.js
![image](https://user-images.githubusercontent.com/17919630/57505167-dbccdb80-7329-11e9-87cf-041d77365337.png)

add 

 modules: true,
 localIdentName: '[local]'

that is ok

**Comment by FleyX** [comment]
I had the save question as you .But then I found a way to solve it.just change the file name from 'Report.less' to 'Report.module.less' and then it will be OK.
