### ISSUE TITLE
...addBabelPresets doest work

### ISSUE THREAD

**Issue by chnirt** [arackaf/customize-cra#97]
![image](https://user-images.githubusercontent.com/35022967/58850482-e5dbc300-86b8-11e9-96bb-61f487b9f931.png)
My issue addBabelPresets not working with my project but when I use useBabelRC() it is Okey ? Explain for me why addbabelPresets not work. Thanks

**Comment by bbouabou** [comment]
Got the same error than you, I have bypassed the problem by doing this : 
```

  ...addBabelPresets(['@babel/preset-typescript']),
  ...addBabelPresets(['@babel/preset-react']),
  ...addBabelPresets([
    '@babel/preset-env',
    {
      modules: 'commonjs',
      targets: {
        browsers: ['> 1%', 'last 2 versions']
      }
    }
  ])
```

**Comment by with-heart** [comment]
Hello! After investigating, I determined that the `readme` incorrectly documented `addbabelPresets` to show that it takes an array of presets, but it should actually take a flat list of arguments.

Correct usage from your example:

```js
module.exports = override(
  ...addBabelPresets(
    [
      "@babel/env",
      {
        targets: {
          browsers: ["> 1%", "last 2 versions"]
        },
        modules: "commonjs"
      }
    ],
    "@babel/preset-flow",
    "@babel/preset-react"
  )
);
```

See #98 for more info

**Comment by arackaf** [comment]
Thanks a ton. Will get this PR merged ASAP.

**Comment by chnirt** [comment]
> Hello! After investigating, I determined that the `readme` incorrectly documented `addbabelPresets` to show that it takes an array of presets, but it should actually take a flat list of arguments.
> 
> Correct usage from your example:
> 
> ```js
> module.exports = override(
>   ...addBabelPresets(
>     [
>       "@babel/env",
>       {
>         targets: {
>           browsers: ["> 1%", "last 2 versions"]
>         },
>         modules: "commonjs"
>       }
>     ],
>     "@babel/preset-flow",
>     "@babel/preset-react"
>   )
> );
> ```
> 
> See #98 for more info

Not run with guy
